{
 "cells": [
  {
   "cell_type": "code",
   "execution_count": null,
   "id": "eb03df4d",
   "metadata": {},
   "outputs": [
    {
     "name": "stdout",
     "output_type": "stream",
     "text": [
      " * Serving Flask app '__main__'\n",
      " * Debug mode: off\n"
     ]
    },
    {
     "name": "stderr",
     "output_type": "stream",
     "text": [
      "WARNING: This is a development server. Do not use it in a production deployment. Use a production WSGI server instead.\n",
      " * Running on http://127.0.0.1:5887\n",
      "Press CTRL+C to quit\n",
      "127.0.0.1 - - [20/Jul/2023 22:45:12] \"GET / HTTP/1.1\" 200 -\n",
      "[2023-07-20 22:45:12,879] ERROR in app: Exception on /get_graph_data [GET]\n",
      "Traceback (most recent call last):\n",
      "  File \"C:\\Users\\Laverne\\anaconda3\\lib\\site-packages\\flask\\app.py\", line 2525, in wsgi_app\n",
      "    response = self.full_dispatch_request()\n",
      "  File \"C:\\Users\\Laverne\\anaconda3\\lib\\site-packages\\flask\\app.py\", line 1822, in full_dispatch_request\n",
      "    rv = self.handle_user_exception(e)\n",
      "  File \"C:\\Users\\Laverne\\anaconda3\\lib\\site-packages\\flask\\app.py\", line 1820, in full_dispatch_request\n",
      "    rv = self.dispatch_request()\n",
      "  File \"C:\\Users\\Laverne\\anaconda3\\lib\\site-packages\\flask\\app.py\", line 1796, in dispatch_request\n",
      "    return self.ensure_sync(self.view_functions[rule.endpoint])(**view_args)\n",
      "  File \"C:\\Users\\Laverne\\AppData\\Local\\Temp\\ipykernel_16992\\1007073488.py\", line 399, in get_graph_data\n",
      "    return jsonify({'graph_src': f'static/graph.jpg?{timestamp}'})\n",
      "NameError: name 'jsonify' is not defined\n",
      "127.0.0.1 - - [20/Jul/2023 22:45:12] \"[2023-07-20 22:45:12,889] ERROR in app: Exception on /get_hist [GET]\n",
      "Traceback (most recent call last):\n",
      "  File \"C:\\Users\\Laverne\\anaconda3\\lib\\site-packages\\flask\\app.py\", line 2525, in wsgi_app\n",
      "    response = self.full_dispatch_request()\n",
      "  File \"C:\\Users\\Laverne\\anaconda3\\lib\\site-packages\\flask\\app.py\", line 1822, in full_dispatch_request\n",
      "    rv = self.handle_user_exception(e)\n",
      "  File \"C:\\Users\\Laverne\\anaconda3\\lib\\site-packages\\flask\\app.py\", line 1820, in full_dispatch_request\n",
      "    rv = self.dispatch_request()\n",
      "  File \"C:\\Users\\Laverne\\anaconda3\\lib\\site-packages\\flask\\app.py\", line 1796, in dispatch_request\n",
      "    return self.ensure_sync(self.view_functions[rule.endpoint])(**view_args)\n",
      "  File \"C:\\Users\\Laverne\\AppData\\Local\\Temp\\ipykernel_16992\\1007073488.py\", line 416, in get_hist\n",
      "    return jsonify({'hist_src': f'static/histogram.jpg?{timestamp}'})\n",
      "NameError: name 'jsonify' is not defined\n",
      "GET /get_graph_data HTTP/1.1\" 500 -\n",
      "127.0.0.1 - - [20/Jul/2023 22:45:12] \"GET /get_hist HTTP/1.1\" 500 -\n",
      "127.0.0.1 - - [20/Jul/2023 22:45:12] \"GET /static/graph.jpg HTTP/1.1\" 304 -\n",
      "[2023-07-20 22:45:13,015] ERROR in app: Exception on /get_hist [GET]\n",
      "Traceback (most recent call last):\n",
      "  File \"C:\\Users\\Laverne\\anaconda3\\lib\\site-packages\\flask\\app.py\", line 2525, in wsgi_app\n",
      "    response = self.full_dispatch_request()\n",
      "  File \"C:\\Users\\Laverne\\anaconda3\\lib\\site-packages\\flask\\app.py\", line 1822, in full_dispatch_request\n",
      "    rv = self.handle_user_exception(e)\n",
      "  File \"C:\\Users\\Laverne\\anaconda3\\lib\\site-packages\\flask\\app.py\", line 1820, in full_dispatch_request\n",
      "    rv = self.dispatch_request()\n",
      "  File \"C:\\Users\\Laverne\\anaconda3\\lib\\site-packages\\flask\\app.py\", line 1796, in dispatch_request\n",
      "    return self.ensure_sync(self.view_functions[rule.endpoint])(**view_args)\n",
      "  File \"C:\\Users\\Laverne\\AppData\\Local\\Temp\\ipykernel_16992\\1007073488.py\", line 416, in get_hist\n",
      "    return jsonify({'hist_src': f'static/histogram.jpg?{timestamp}'})\n",
      "NameError: name 'jsonify' is not defined\n",
      "127.0.0.1 - - [20/Jul/2023 22:45:13] \"GET /get_hist HTTP/1.1\" 500 -\n",
      "127.0.0.1 - - [20/Jul/2023 22:45:13] \"GET /static/histogram.jpg HTTP/1.1\" 304 -\n",
      "[2023-07-20 22:45:14,945] ERROR in app: Exception on /get_graph_data [GET]\n",
      "Traceback (most recent call last):\n",
      "  File \"C:\\Users\\Laverne\\anaconda3\\lib\\site-packages\\flask\\app.py\", line 2525, in wsgi_app\n",
      "    response = self.full_dispatch_request()\n",
      "  File \"C:\\Users\\Laverne\\anaconda3\\lib\\site-packages\\flask\\app.py\", line 1822, in full_dispatch_request\n",
      "    rv = self.handle_user_exception(e)\n",
      "  File \"C:\\Users\\Laverne\\anaconda3\\lib\\site-packages\\flask\\app.py\", line 1820, in full_dispatch_request\n",
      "    rv = self.dispatch_request()\n",
      "  File \"C:\\Users\\Laverne\\anaconda3\\lib\\site-packages\\flask\\app.py\", line 1796, in dispatch_request\n",
      "    return self.ensure_sync(self.view_functions[rule.endpoint])(**view_args)\n",
      "  File \"C:\\Users\\Laverne\\AppData\\Local\\Temp\\ipykernel_16992\\1007073488.py\", line 399, in get_graph_data\n",
      "    return jsonify({'graph_src': f'static/graph.jpg?{timestamp}'})\n",
      "NameError: name 'jsonify' is not defined\n",
      "127.0.0.1 - - [20/Jul/2023 22:45:14] \"GET /get_graph_data HTTP/1.1\" 500 -\n",
      "[2023-07-20 22:45:16,961] ERROR in app: Exception on /get_hist [GET]\n",
      "Traceback (most recent call last):\n",
      "  File \"C:\\Users\\Laverne\\anaconda3\\lib\\site-packages\\flask\\app.py\", line 2525, in wsgi_app\n",
      "    response = self.full_dispatch_request()\n",
      "  File \"C:\\Users\\Laverne\\anaconda3\\lib\\site-packages\\flask\\app.py\", line 1822, in full_dispatch_request\n",
      "    rv = self.handle_user_exception(e)\n",
      "  File \"C:\\Users\\Laverne\\anaconda3\\lib\\site-packages\\flask\\app.py\", line 1820, in full_dispatch_request\n",
      "    rv = self.dispatch_request()\n",
      "  File \"C:\\Users\\Laverne\\anaconda3\\lib\\site-packages\\flask\\app.py\", line 1796, in dispatch_request\n",
      "    return self.ensure_sync(self.view_functions[rule.endpoint])(**view_args)\n",
      "  File \"C:\\Users\\Laverne\\AppData\\Local\\Temp\\ipykernel_16992\\1007073488.py\", line 416, in get_hist\n",
      "    return jsonify({'hist_src': f'static/histogram.jpg?{timestamp}'})\n",
      "NameError: name 'jsonify' is not defined\n",
      "127.0.0.1 - - [20/Jul/2023 22:45:16] \"GET /get_hist HTTP/1.1\" 500 -\n",
      "[2023-07-20 22:45:16,984] ERROR in app: Exception on /get_graph_data [GET]\n",
      "Traceback (most recent call last):\n",
      "  File \"C:\\Users\\Laverne\\anaconda3\\lib\\site-packages\\flask\\app.py\", line 2525, in wsgi_app\n",
      "    response = self.full_dispatch_request()\n",
      "  File \"C:\\Users\\Laverne\\anaconda3\\lib\\site-packages\\flask\\app.py\", line 1822, in full_dispatch_request\n",
      "    rv = self.handle_user_exception(e)\n",
      "  File \"C:\\Users\\Laverne\\anaconda3\\lib\\site-packages\\flask\\app.py\", line 1820, in full_dispatch_request\n",
      "    rv = self.dispatch_request()\n",
      "  File \"C:\\Users\\Laverne\\anaconda3\\lib\\site-packages\\flask\\app.py\", line 1796, in dispatch_request\n",
      "    return self.ensure_sync(self.view_functions[rule.endpoint])(**view_args)\n",
      "  File \"C:\\Users\\Laverne\\AppData\\Local\\Temp\\ipykernel_16992\\1007073488.py\", line 399, in get_graph_data\n",
      "    return jsonify({'graph_src': f'static/graph.jpg?{timestamp}'})\n",
      "NameError: name 'jsonify' is not defined\n",
      "127.0.0.1 - - [20/Jul/2023 22:45:16] \"GET /get_graph_data HTTP/1.1\" 500 -\n",
      "[2023-07-20 22:45:17,053] ERROR in app: Exception on /get_hist [GET]\n",
      "Traceback (most recent call last):\n",
      "  File \"C:\\Users\\Laverne\\anaconda3\\lib\\site-packages\\flask\\app.py\", line 2525, in wsgi_app\n",
      "    response = self.full_dispatch_request()\n",
      "  File \"C:\\Users\\Laverne\\anaconda3\\lib\\site-packages\\flask\\app.py\", line 1822, in full_dispatch_request\n",
      "    rv = self.handle_user_exception(e)\n",
      "  File \"C:\\Users\\Laverne\\anaconda3\\lib\\site-packages\\flask\\app.py\", line 1820, in full_dispatch_request\n",
      "    rv = self.dispatch_request()\n",
      "  File \"C:\\Users\\Laverne\\anaconda3\\lib\\site-packages\\flask\\app.py\", line 1796, in dispatch_request\n",
      "    return self.ensure_sync(self.view_functions[rule.endpoint])(**view_args)\n",
      "  File \"C:\\Users\\Laverne\\AppData\\Local\\Temp\\ipykernel_16992\\1007073488.py\", line 416, in get_hist\n",
      "    return jsonify({'hist_src': f'static/histogram.jpg?{timestamp}'})\n",
      "NameError: name 'jsonify' is not defined\n",
      "127.0.0.1 - - [20/Jul/2023 22:45:17] \"GET /get_hist HTTP/1.1\" 500 -\n",
      "[2023-07-20 22:45:19,030] ERROR in app: Exception on /get_graph_data [GET]\n",
      "Traceback (most recent call last):\n",
      "  File \"C:\\Users\\Laverne\\anaconda3\\lib\\site-packages\\flask\\app.py\", line 2525, in wsgi_app\n",
      "    response = self.full_dispatch_request()\n",
      "  File \"C:\\Users\\Laverne\\anaconda3\\lib\\site-packages\\flask\\app.py\", line 1822, in full_dispatch_request\n",
      "    rv = self.handle_user_exception(e)\n",
      "  File \"C:\\Users\\Laverne\\anaconda3\\lib\\site-packages\\flask\\app.py\", line 1820, in full_dispatch_request\n",
      "    rv = self.dispatch_request()\n",
      "  File \"C:\\Users\\Laverne\\anaconda3\\lib\\site-packages\\flask\\app.py\", line 1796, in dispatch_request\n",
      "    return self.ensure_sync(self.view_functions[rule.endpoint])(**view_args)\n",
      "  File \"C:\\Users\\Laverne\\AppData\\Local\\Temp\\ipykernel_16992\\1007073488.py\", line 399, in get_graph_data\n",
      "    return jsonify({'graph_src': f'static/graph.jpg?{timestamp}'})\n",
      "NameError: name 'jsonify' is not defined\n"
     ]
    },
    {
     "name": "stderr",
     "output_type": "stream",
     "text": [
      "127.0.0.1 - - [20/Jul/2023 22:45:19] \"GET /get_graph_data HTTP/1.1\" 500 -\n",
      "[2023-07-20 22:45:21,011] ERROR in app: Exception on /get_hist [GET]\n",
      "Traceback (most recent call last):\n",
      "  File \"C:\\Users\\Laverne\\anaconda3\\lib\\site-packages\\flask\\app.py\", line 2525, in wsgi_app\n",
      "    response = self.full_dispatch_request()\n",
      "  File \"C:\\Users\\Laverne\\anaconda3\\lib\\site-packages\\flask\\app.py\", line 1822, in full_dispatch_request\n",
      "    rv = self.handle_user_exception(e)\n",
      "  File \"C:\\Users\\Laverne\\anaconda3\\lib\\site-packages\\flask\\app.py\", line 1820, in full_dispatch_request\n",
      "    rv = self.dispatch_request()\n",
      "  File \"C:\\Users\\Laverne\\anaconda3\\lib\\site-packages\\flask\\app.py\", line 1796, in dispatch_request\n",
      "    return self.ensure_sync(self.view_functions[rule.endpoint])(**view_args)\n",
      "  File \"C:\\Users\\Laverne\\AppData\\Local\\Temp\\ipykernel_16992\\1007073488.py\", line 416, in get_hist\n",
      "    return jsonify({'hist_src': f'static/histogram.jpg?{timestamp}'})\n",
      "NameError: name 'jsonify' is not defined\n",
      "127.0.0.1 - - [20/Jul/2023 22:45:21] \"GET /get_hist HTTP/1.1\" 500 -\n",
      "[2023-07-20 22:45:21,057] ERROR in app: Exception on /get_graph_data [GET]\n",
      "Traceback (most recent call last):\n",
      "  File \"C:\\Users\\Laverne\\anaconda3\\lib\\site-packages\\flask\\app.py\", line 2525, in wsgi_app\n",
      "    response = self.full_dispatch_request()\n",
      "  File \"C:\\Users\\Laverne\\anaconda3\\lib\\site-packages\\flask\\app.py\", line 1822, in full_dispatch_request\n",
      "    rv = self.handle_user_exception(e)\n",
      "  File \"C:\\Users\\Laverne\\anaconda3\\lib\\site-packages\\flask\\app.py\", line 1820, in full_dispatch_request\n",
      "    rv = self.dispatch_request()\n",
      "  File \"C:\\Users\\Laverne\\anaconda3\\lib\\site-packages\\flask\\app.py\", line 1796, in dispatch_request\n",
      "    return self.ensure_sync(self.view_functions[rule.endpoint])(**view_args)\n",
      "  File \"C:\\Users\\Laverne\\AppData\\Local\\Temp\\ipykernel_16992\\1007073488.py\", line 399, in get_graph_data\n",
      "    return jsonify({'graph_src': f'static/graph.jpg?{timestamp}'})\n",
      "NameError: name 'jsonify' is not defined\n",
      "127.0.0.1 - - [20/Jul/2023 22:45:21] \"GET /get_graph_data HTTP/1.1\" 500 -\n",
      "[2023-07-20 22:45:21,096] ERROR in app: Exception on /get_hist [GET]\n",
      "Traceback (most recent call last):\n",
      "  File \"C:\\Users\\Laverne\\anaconda3\\lib\\site-packages\\flask\\app.py\", line 2525, in wsgi_app\n",
      "    response = self.full_dispatch_request()\n",
      "  File \"C:\\Users\\Laverne\\anaconda3\\lib\\site-packages\\flask\\app.py\", line 1822, in full_dispatch_request\n",
      "    rv = self.handle_user_exception(e)\n",
      "  File \"C:\\Users\\Laverne\\anaconda3\\lib\\site-packages\\flask\\app.py\", line 1820, in full_dispatch_request\n",
      "    rv = self.dispatch_request()\n",
      "  File \"C:\\Users\\Laverne\\anaconda3\\lib\\site-packages\\flask\\app.py\", line 1796, in dispatch_request\n",
      "    return self.ensure_sync(self.view_functions[rule.endpoint])(**view_args)\n",
      "  File \"C:\\Users\\Laverne\\AppData\\Local\\Temp\\ipykernel_16992\\1007073488.py\", line 416, in get_hist\n",
      "    return jsonify({'hist_src': f'static/histogram.jpg?{timestamp}'})\n",
      "NameError: name 'jsonify' is not defined\n",
      "127.0.0.1 - - [20/Jul/2023 22:45:21] \"GET /get_hist HTTP/1.1\" 500 -\n",
      "[2023-07-20 22:45:23,092] ERROR in app: Exception on /get_graph_data [GET]\n",
      "Traceback (most recent call last):\n",
      "  File \"C:\\Users\\Laverne\\anaconda3\\lib\\site-packages\\flask\\app.py\", line 2525, in wsgi_app\n",
      "    response = self.full_dispatch_request()\n",
      "  File \"C:\\Users\\Laverne\\anaconda3\\lib\\site-packages\\flask\\app.py\", line 1822, in full_dispatch_request\n",
      "    rv = self.handle_user_exception(e)\n",
      "  File \"C:\\Users\\Laverne\\anaconda3\\lib\\site-packages\\flask\\app.py\", line 1820, in full_dispatch_request\n",
      "    rv = self.dispatch_request()\n",
      "  File \"C:\\Users\\Laverne\\anaconda3\\lib\\site-packages\\flask\\app.py\", line 1796, in dispatch_request\n",
      "    return self.ensure_sync(self.view_functions[rule.endpoint])(**view_args)\n",
      "  File \"C:\\Users\\Laverne\\AppData\\Local\\Temp\\ipykernel_16992\\1007073488.py\", line 399, in get_graph_data\n",
      "    return jsonify({'graph_src': f'static/graph.jpg?{timestamp}'})\n",
      "NameError: name 'jsonify' is not defined\n",
      "127.0.0.1 - - [20/Jul/2023 22:45:23] \"GET /get_graph_data HTTP/1.1\" 500 -\n",
      "[2023-07-20 22:45:25,041] ERROR in app: Exception on /get_hist [GET]\n",
      "Traceback (most recent call last):\n",
      "  File \"C:\\Users\\Laverne\\anaconda3\\lib\\site-packages\\flask\\app.py\", line 2525, in wsgi_app\n",
      "    response = self.full_dispatch_request()\n",
      "  File \"C:\\Users\\Laverne\\anaconda3\\lib\\site-packages\\flask\\app.py\", line 1822, in full_dispatch_request\n",
      "    rv = self.handle_user_exception(e)\n",
      "  File \"C:\\Users\\Laverne\\anaconda3\\lib\\site-packages\\flask\\app.py\", line 1820, in full_dispatch_request\n",
      "    rv = self.dispatch_request()\n",
      "  File \"C:\\Users\\Laverne\\anaconda3\\lib\\site-packages\\flask\\app.py\", line 1796, in dispatch_request\n",
      "    return self.ensure_sync(self.view_functions[rule.endpoint])(**view_args)\n",
      "  File \"C:\\Users\\Laverne\\AppData\\Local\\Temp\\ipykernel_16992\\1007073488.py\", line 416, in get_hist\n",
      "    return jsonify({'hist_src': f'static/histogram.jpg?{timestamp}'})\n",
      "NameError: name 'jsonify' is not defined\n",
      "127.0.0.1 - - [20/Jul/2023 22:45:25] \"GET /get_hist HTTP/1.1\" 500 -\n",
      "[2023-07-20 22:45:25,124] ERROR in app: Exception on /get_graph_data [GET]\n",
      "Traceback (most recent call last):\n",
      "  File \"C:\\Users\\Laverne\\anaconda3\\lib\\site-packages\\flask\\app.py\", line 2525, in wsgi_app\n",
      "    response = self.full_dispatch_request()\n",
      "  File \"C:\\Users\\Laverne\\anaconda3\\lib\\site-packages\\flask\\app.py\", line 1822, in full_dispatch_request\n",
      "    rv = self.handle_user_exception(e)\n",
      "  File \"C:\\Users\\Laverne\\anaconda3\\lib\\site-packages\\flask\\app.py\", line 1820, in full_dispatch_request\n",
      "    rv = self.dispatch_request()\n",
      "  File \"C:\\Users\\Laverne\\anaconda3\\lib\\site-packages\\flask\\app.py\", line 1796, in dispatch_request\n",
      "    return self.ensure_sync(self.view_functions[rule.endpoint])(**view_args)\n",
      "  File \"C:\\Users\\Laverne\\AppData\\Local\\Temp\\ipykernel_16992\\1007073488.py\", line 399, in get_graph_data\n",
      "    return jsonify({'graph_src': f'static/graph.jpg?{timestamp}'})\n",
      "NameError: name 'jsonify' is not defined\n",
      "127.0.0.1 - - [20/Jul/2023 22:45:25] \"GET /get_graph_data HTTP/1.1\" 500 -\n",
      "[2023-07-20 22:45:25,145] ERROR in app: Exception on /get_hist [GET]\n",
      "Traceback (most recent call last):\n",
      "  File \"C:\\Users\\Laverne\\anaconda3\\lib\\site-packages\\flask\\app.py\", line 2525, in wsgi_app\n",
      "    response = self.full_dispatch_request()\n",
      "  File \"C:\\Users\\Laverne\\anaconda3\\lib\\site-packages\\flask\\app.py\", line 1822, in full_dispatch_request\n",
      "    rv = self.handle_user_exception(e)\n",
      "  File \"C:\\Users\\Laverne\\anaconda3\\lib\\site-packages\\flask\\app.py\", line 1820, in full_dispatch_request\n",
      "    rv = self.dispatch_request()\n",
      "  File \"C:\\Users\\Laverne\\anaconda3\\lib\\site-packages\\flask\\app.py\", line 1796, in dispatch_request\n",
      "    return self.ensure_sync(self.view_functions[rule.endpoint])(**view_args)\n",
      "  File \"C:\\Users\\Laverne\\AppData\\Local\\Temp\\ipykernel_16992\\1007073488.py\", line 416, in get_hist\n",
      "    return jsonify({'hist_src': f'static/histogram.jpg?{timestamp}'})\n",
      "NameError: name 'jsonify' is not defined\n",
      "127.0.0.1 - - [20/Jul/2023 22:45:25] \"GET /get_hist HTTP/1.1\" 500 -\n",
      "[2023-07-20 22:45:27,164] ERROR in app: Exception on /get_graph_data [GET]\n",
      "Traceback (most recent call last):\n",
      "  File \"C:\\Users\\Laverne\\anaconda3\\lib\\site-packages\\flask\\app.py\", line 2525, in wsgi_app\n",
      "    response = self.full_dispatch_request()\n",
      "  File \"C:\\Users\\Laverne\\anaconda3\\lib\\site-packages\\flask\\app.py\", line 1822, in full_dispatch_request\n",
      "    rv = self.handle_user_exception(e)\n",
      "  File \"C:\\Users\\Laverne\\anaconda3\\lib\\site-packages\\flask\\app.py\", line 1820, in full_dispatch_request\n",
      "    rv = self.dispatch_request()\n",
      "  File \"C:\\Users\\Laverne\\anaconda3\\lib\\site-packages\\flask\\app.py\", line 1796, in dispatch_request\n",
      "    return self.ensure_sync(self.view_functions[rule.endpoint])(**view_args)\n",
      "  File \"C:\\Users\\Laverne\\AppData\\Local\\Temp\\ipykernel_16992\\1007073488.py\", line 399, in get_graph_data\n",
      "    return jsonify({'graph_src': f'static/graph.jpg?{timestamp}'})\n",
      "NameError: name 'jsonify' is not defined\n",
      "127.0.0.1 - - [20/Jul/2023 22:45:27] \"GET /get_graph_data HTTP/1.1\" 500 -\n",
      "[2023-07-20 22:45:29,077] ERROR in app: Exception on /get_hist [GET]\n",
      "Traceback (most recent call last):\n",
      "  File \"C:\\Users\\Laverne\\anaconda3\\lib\\site-packages\\flask\\app.py\", line 2525, in wsgi_app\n",
      "    response = self.full_dispatch_request()\n",
      "  File \"C:\\Users\\Laverne\\anaconda3\\lib\\site-packages\\flask\\app.py\", line 1822, in full_dispatch_request\n",
      "    rv = self.handle_user_exception(e)\n",
      "  File \"C:\\Users\\Laverne\\anaconda3\\lib\\site-packages\\flask\\app.py\", line 1820, in full_dispatch_request\n",
      "    rv = self.dispatch_request()\n",
      "  File \"C:\\Users\\Laverne\\anaconda3\\lib\\site-packages\\flask\\app.py\", line 1796, in dispatch_request\n",
      "    return self.ensure_sync(self.view_functions[rule.endpoint])(**view_args)\n",
      "  File \"C:\\Users\\Laverne\\AppData\\Local\\Temp\\ipykernel_16992\\1007073488.py\", line 416, in get_hist\n",
      "    return jsonify({'hist_src': f'static/histogram.jpg?{timestamp}'})\n",
      "NameError: name 'jsonify' is not defined\n"
     ]
    },
    {
     "name": "stderr",
     "output_type": "stream",
     "text": [
      "127.0.0.1 - - [20/Jul/2023 22:45:29] \"GET /get_hist HTTP/1.1\" 500 -\n",
      "[2023-07-20 22:45:29,184] ERROR in app: Exception on /get_hist [GET]\n",
      "Traceback (most recent call last):\n",
      "  File \"C:\\Users\\Laverne\\anaconda3\\lib\\site-packages\\flask\\app.py\", line 2525, in wsgi_app\n",
      "    response = self.full_dispatch_request()\n",
      "  File \"C:\\Users\\Laverne\\anaconda3\\lib\\site-packages\\flask\\app.py\", line 1822, in full_dispatch_request\n",
      "    rv = self.handle_user_exception(e)\n",
      "  File \"C:\\Users\\Laverne\\anaconda3\\lib\\site-packages\\flask\\app.py\", line 1820, in full_dispatch_request\n",
      "    rv = self.dispatch_request()\n",
      "  File \"C:\\Users\\Laverne\\anaconda3\\lib\\site-packages\\flask\\app.py\", line 1796, in dispatch_request\n",
      "    return self.ensure_sync(self.view_functions[rule.endpoint])(**view_args)\n",
      "  File \"C:\\Users\\Laverne\\AppData\\Local\\Temp\\ipykernel_16992\\1007073488.py\", line 416, in get_hist\n",
      "    return jsonify({'hist_src': f'static/histogram.jpg?{timestamp}'})\n",
      "NameError: name 'jsonify' is not defined\n",
      "127.0.0.1 - - [20/Jul/2023 22:45:29] \"GET /get_hist HTTP/1.1\" 500 -\n",
      "[2023-07-20 22:45:29,248] ERROR in app: Exception on /get_graph_data [GET]\n",
      "Traceback (most recent call last):\n",
      "  File \"C:\\Users\\Laverne\\anaconda3\\lib\\site-packages\\flask\\app.py\", line 2525, in wsgi_app\n",
      "    response = self.full_dispatch_request()\n",
      "  File \"C:\\Users\\Laverne\\anaconda3\\lib\\site-packages\\flask\\app.py\", line 1822, in full_dispatch_request\n",
      "    rv = self.handle_user_exception(e)\n",
      "  File \"C:\\Users\\Laverne\\anaconda3\\lib\\site-packages\\flask\\app.py\", line 1820, in full_dispatch_request\n",
      "    rv = self.dispatch_request()\n",
      "  File \"C:\\Users\\Laverne\\anaconda3\\lib\\site-packages\\flask\\app.py\", line 1796, in dispatch_request\n",
      "    return self.ensure_sync(self.view_functions[rule.endpoint])(**view_args)\n",
      "  File \"C:\\Users\\Laverne\\AppData\\Local\\Temp\\ipykernel_16992\\1007073488.py\", line 399, in get_graph_data\n",
      "    return jsonify({'graph_src': f'static/graph.jpg?{timestamp}'})\n",
      "NameError: name 'jsonify' is not defined\n",
      "127.0.0.1 - - [20/Jul/2023 22:45:29] \"GET /get_graph_data HTTP/1.1\" 500 -\n",
      "[2023-07-20 22:45:32,226] ERROR in app: Exception on /get_graph_data [GET]\n",
      "Traceback (most recent call last):\n",
      "  File \"C:\\Users\\Laverne\\anaconda3\\lib\\site-packages\\flask\\app.py\", line 2525, in wsgi_app\n",
      "    response = self.full_dispatch_request()\n",
      "  File \"C:\\Users\\Laverne\\anaconda3\\lib\\site-packages\\flask\\app.py\", line 1822, in full_dispatch_request\n",
      "    rv = self.handle_user_exception(e)\n",
      "  File \"C:\\Users\\Laverne\\anaconda3\\lib\\site-packages\\flask\\app.py\", line 1820, in full_dispatch_request\n",
      "    rv = self.dispatch_request()\n",
      "  File \"C:\\Users\\Laverne\\anaconda3\\lib\\site-packages\\flask\\app.py\", line 1796, in dispatch_request\n",
      "    return self.ensure_sync(self.view_functions[rule.endpoint])(**view_args)\n",
      "  File \"C:\\Users\\Laverne\\AppData\\Local\\Temp\\ipykernel_16992\\1007073488.py\", line 399, in get_graph_data\n",
      "    return jsonify({'graph_src': f'static/graph.jpg?{timestamp}'})\n",
      "NameError: name 'jsonify' is not defined\n",
      "127.0.0.1 - - [20/Jul/2023 22:45:32] \"GET /get_graph_data HTTP/1.1\" 500 -\n",
      "[2023-07-20 22:45:33,217] ERROR in app: Exception on /get_hist [GET]\n",
      "Traceback (most recent call last):\n",
      "  File \"C:\\Users\\Laverne\\anaconda3\\lib\\site-packages\\flask\\app.py\", line 2525, in wsgi_app\n",
      "    response = self.full_dispatch_request()\n",
      "  File \"C:\\Users\\Laverne\\anaconda3\\lib\\site-packages\\flask\\app.py\", line 1822, in full_dispatch_request\n",
      "    rv = self.handle_user_exception(e)\n",
      "  File \"C:\\Users\\Laverne\\anaconda3\\lib\\site-packages\\flask\\app.py\", line 1820, in full_dispatch_request\n",
      "    rv = self.dispatch_request()\n",
      "  File \"C:\\Users\\Laverne\\anaconda3\\lib\\site-packages\\flask\\app.py\", line 1796, in dispatch_request\n",
      "    return self.ensure_sync(self.view_functions[rule.endpoint])(**view_args)\n",
      "  File \"C:\\Users\\Laverne\\AppData\\Local\\Temp\\ipykernel_16992\\1007073488.py\", line 416, in get_hist\n",
      "    return jsonify({'hist_src': f'static/histogram.jpg?{timestamp}'})\n",
      "NameError: name 'jsonify' is not defined\n",
      "127.0.0.1 - - [20/Jul/2023 22:45:33] \"GET /get_hist HTTP/1.1\" 500 -\n",
      "127.0.0.1 - - [20/Jul/2023 22:45:34] \"POST / HTTP/1.1\" 200 -\n",
      "[2023-07-20 22:45:34,201] ERROR in app: Exception on /get_hist [GET]\n",
      "Traceback (most recent call last):\n",
      "  File \"C:\\Users\\Laverne\\anaconda3\\lib\\site-packages\\flask\\app.py\", line 2525, in wsgi_app\n",
      "    response = self.full_dispatch_request()\n",
      "  File \"C:\\Users\\Laverne\\anaconda3\\lib\\site-packages\\flask\\app.py\", line 1822, in full_dispatch_request\n",
      "    rv = self.handle_user_exception(e)\n",
      "  File \"C:\\Users\\Laverne\\anaconda3\\lib\\site-packages\\flask\\app.py\", line 1820, in full_dispatch_request\n",
      "    rv = self.dispatch_request()\n",
      "  File \"C:\\Users\\Laverne\\anaconda3\\lib\\site-packages\\flask\\app.py\", line 1796, in dispatch_request\n",
      "    return self.ensure_sync(self.view_functions[rule.endpoint])(**view_args)\n",
      "  File \"C:\\Users\\Laverne\\AppData\\Local\\Temp\\ipykernel_16992\\1007073488.py\", line 416, in get_hist\n",
      "    return jsonify({'hist_src': f'static/histogram.jpg?{timestamp}'})\n",
      "NameError: name 'jsonify' is not defined\n",
      "127.0.0.1 - - [20/Jul/2023 22:45:34] \"GET /get_hist HTTP/1.1\" 500 -\n",
      "127.0.0.1 - - [20/Jul/2023 22:45:34] \"GET /static/histogram.jpg HTTP/1.1\" 304 -\n",
      "127.0.0.1 - - [20/Jul/2023 22:45:34] \"GET /static/graph.jpg HTTP/1.1\" 304 -\n",
      "[2023-07-20 22:45:34,463] ERROR in app: Exception on /get_graph_data [GET]\n",
      "Traceback (most recent call last):\n",
      "  File \"C:\\Users\\Laverne\\anaconda3\\lib\\site-packages\\flask\\app.py\", line 2525, in wsgi_app\n",
      "    response = self.full_dispatch_request()\n",
      "  File \"C:\\Users\\Laverne\\anaconda3\\lib\\site-packages\\flask\\app.py\", line 1822, in full_dispatch_request\n",
      "    rv = self.handle_user_exception(e)\n",
      "  File \"C:\\Users\\Laverne\\anaconda3\\lib\\site-packages\\flask\\app.py\", line 1820, in full_dispatch_request\n",
      "    rv = self.dispatch_request()\n",
      "  File \"C:\\Users\\Laverne\\anaconda3\\lib\\site-packages\\flask\\app.py\", line 1796, in dispatch_request\n",
      "    return self.ensure_sync(self.view_functions[rule.endpoint])(**view_args)\n",
      "  File \"C:\\Users\\Laverne\\AppData\\Local\\Temp\\ipykernel_16992\\1007073488.py\", line 399, in get_graph_data\n",
      "    return jsonify({'graph_src': f'static/graph.jpg?{timestamp}'})\n",
      "NameError: name 'jsonify' is not defined\n",
      "127.0.0.1 - - [20/Jul/2023 22:45:34] \"GET /get_graph_data HTTP/1.1\" 500 -\n",
      "[2023-07-20 22:45:34,543] ERROR in app: Exception on /get_hist [GET]\n",
      "Traceback (most recent call last):\n",
      "  File \"C:\\Users\\Laverne\\anaconda3\\lib\\site-packages\\flask\\app.py\", line 2525, in wsgi_app\n",
      "    response = self.full_dispatch_request()\n",
      "  File \"C:\\Users\\Laverne\\anaconda3\\lib\\site-packages\\flask\\app.py\", line 1822, in full_dispatch_request\n",
      "    rv = self.handle_user_exception(e)\n",
      "  File \"C:\\Users\\Laverne\\anaconda3\\lib\\site-packages\\flask\\app.py\", line 1820, in full_dispatch_request\n",
      "    rv = self.dispatch_request()\n",
      "  File \"C:\\Users\\Laverne\\anaconda3\\lib\\site-packages\\flask\\app.py\", line 1796, in dispatch_request\n",
      "    return self.ensure_sync(self.view_functions[rule.endpoint])(**view_args)\n",
      "  File \"C:\\Users\\Laverne\\AppData\\Local\\Temp\\ipykernel_16992\\1007073488.py\", line 416, in get_hist\n",
      "    return jsonify({'hist_src': f'static/histogram.jpg?{timestamp}'})\n",
      "NameError: name 'jsonify' is not defined\n",
      "127.0.0.1 - - [20/Jul/2023 22:45:34] \"GET /get_hist HTTP/1.1\" 500 -\n",
      "[2023-07-20 22:45:34,578] ERROR in app: Exception on /get_hist [GET]\n",
      "Traceback (most recent call last):\n",
      "  File \"C:\\Users\\Laverne\\anaconda3\\lib\\site-packages\\flask\\app.py\", line 2525, in wsgi_app\n",
      "    response = self.full_dispatch_request()\n",
      "  File \"C:\\Users\\Laverne\\anaconda3\\lib\\site-packages\\flask\\app.py\", line 1822, in full_dispatch_request\n",
      "    rv = self.handle_user_exception(e)\n",
      "  File \"C:\\Users\\Laverne\\anaconda3\\lib\\site-packages\\flask\\app.py\", line 1820, in full_dispatch_request\n",
      "    rv = self.dispatch_request()\n",
      "  File \"C:\\Users\\Laverne\\anaconda3\\lib\\site-packages\\flask\\app.py\", line 1796, in dispatch_request\n",
      "    return self.ensure_sync(self.view_functions[rule.endpoint])(**view_args)\n",
      "  File \"C:\\Users\\Laverne\\AppData\\Local\\Temp\\ipykernel_16992\\1007073488.py\", line 416, in get_hist\n",
      "    return jsonify({'hist_src': f'static/histogram.jpg?{timestamp}'})\n",
      "NameError: name 'jsonify' is not defined\n",
      "127.0.0.1 - - [20/Jul/2023 22:45:34] \"GET /get_hist HTTP/1.1\" 500 -\n",
      "[2023-07-20 22:45:36,524] ERROR in app: Exception on /get_graph_data [GET]\n",
      "Traceback (most recent call last):\n",
      "  File \"C:\\Users\\Laverne\\anaconda3\\lib\\site-packages\\flask\\app.py\", line 2525, in wsgi_app\n",
      "    response = self.full_dispatch_request()\n",
      "  File \"C:\\Users\\Laverne\\anaconda3\\lib\\site-packages\\flask\\app.py\", line 1822, in full_dispatch_request\n",
      "    rv = self.handle_user_exception(e)\n",
      "  File \"C:\\Users\\Laverne\\anaconda3\\lib\\site-packages\\flask\\app.py\", line 1820, in full_dispatch_request\n",
      "    rv = self.dispatch_request()\n",
      "  File \"C:\\Users\\Laverne\\anaconda3\\lib\\site-packages\\flask\\app.py\", line 1796, in dispatch_request\n",
      "    return self.ensure_sync(self.view_functions[rule.endpoint])(**view_args)\n",
      "  File \"C:\\Users\\Laverne\\AppData\\Local\\Temp\\ipykernel_16992\\1007073488.py\", line 399, in get_graph_data\n",
      "    return jsonify({'graph_src': f'static/graph.jpg?{timestamp}'})\n",
      "NameError: name 'jsonify' is not defined\n"
     ]
    },
    {
     "name": "stderr",
     "output_type": "stream",
     "text": [
      "127.0.0.1 - - [20/Jul/2023 22:45:36] \"GET /get_graph_data HTTP/1.1\" 500 -\n",
      "[2023-07-20 22:45:38,556] ERROR in app: Exception on /get_graph_data [GET]\n",
      "Traceback (most recent call last):\n",
      "  File \"C:\\Users\\Laverne\\anaconda3\\lib\\site-packages\\flask\\app.py\", line 2525, in wsgi_app\n",
      "    response = self.full_dispatch_request()\n",
      "  File \"C:\\Users\\Laverne\\anaconda3\\lib\\site-packages\\flask\\app.py\", line 1822, in full_dispatch_request\n",
      "    rv = self.handle_user_exception(e)\n",
      "  File \"C:\\Users\\Laverne\\anaconda3\\lib\\site-packages\\flask\\app.py\", line 1820, in full_dispatch_request\n",
      "    rv = self.dispatch_request()\n",
      "  File \"C:\\Users\\Laverne\\anaconda3\\lib\\site-packages\\flask\\app.py\", line 1796, in dispatch_request\n",
      "    return self.ensure_sync(self.view_functions[rule.endpoint])(**view_args)\n",
      "  File \"C:\\Users\\Laverne\\AppData\\Local\\Temp\\ipykernel_16992\\1007073488.py\", line 399, in get_graph_data\n",
      "    return jsonify({'graph_src': f'static/graph.jpg?{timestamp}'})\n",
      "NameError: name 'jsonify' is not defined\n",
      "127.0.0.1 - - [20/Jul/2023 22:45:38] \"GET /get_graph_data HTTP/1.1\" 500 -\n",
      "[2023-07-20 22:45:38,579] ERROR in app: Exception on /get_hist [GET]\n",
      "Traceback (most recent call last):\n",
      "  File \"C:\\Users\\Laverne\\anaconda3\\lib\\site-packages\\flask\\app.py\", line 2525, in wsgi_app\n",
      "    response = self.full_dispatch_request()\n",
      "  File \"C:\\Users\\Laverne\\anaconda3\\lib\\site-packages\\flask\\app.py\", line 1822, in full_dispatch_request\n",
      "    rv = self.handle_user_exception(e)\n",
      "  File \"C:\\Users\\Laverne\\anaconda3\\lib\\site-packages\\flask\\app.py\", line 1820, in full_dispatch_request\n",
      "    rv = self.dispatch_request()\n",
      "  File \"C:\\Users\\Laverne\\anaconda3\\lib\\site-packages\\flask\\app.py\", line 1796, in dispatch_request\n",
      "    return self.ensure_sync(self.view_functions[rule.endpoint])(**view_args)\n",
      "  File \"C:\\Users\\Laverne\\AppData\\Local\\Temp\\ipykernel_16992\\1007073488.py\", line 416, in get_hist\n",
      "    return jsonify({'hist_src': f'static/histogram.jpg?{timestamp}'})\n",
      "NameError: name 'jsonify' is not defined\n",
      "127.0.0.1 - - [20/Jul/2023 22:45:38] \"GET /get_hist HTTP/1.1\" 500 -\n",
      "[2023-07-20 22:45:38,607] ERROR in app: Exception on /get_hist [GET]\n",
      "Traceback (most recent call last):\n",
      "  File \"C:\\Users\\Laverne\\anaconda3\\lib\\site-packages\\flask\\app.py\", line 2525, in wsgi_app\n",
      "    response = self.full_dispatch_request()\n",
      "  File \"C:\\Users\\Laverne\\anaconda3\\lib\\site-packages\\flask\\app.py\", line 1822, in full_dispatch_request\n",
      "    rv = self.handle_user_exception(e)\n",
      "  File \"C:\\Users\\Laverne\\anaconda3\\lib\\site-packages\\flask\\app.py\", line 1820, in full_dispatch_request\n",
      "    rv = self.dispatch_request()\n",
      "  File \"C:\\Users\\Laverne\\anaconda3\\lib\\site-packages\\flask\\app.py\", line 1796, in dispatch_request\n",
      "    return self.ensure_sync(self.view_functions[rule.endpoint])(**view_args)\n",
      "  File \"C:\\Users\\Laverne\\AppData\\Local\\Temp\\ipykernel_16992\\1007073488.py\", line 416, in get_hist\n",
      "    return jsonify({'hist_src': f'static/histogram.jpg?{timestamp}'})\n",
      "NameError: name 'jsonify' is not defined\n",
      "127.0.0.1 - - [20/Jul/2023 22:45:38] \"GET /get_hist HTTP/1.1\" 500 -\n",
      "[2023-07-20 22:45:41,205] ERROR in app: Exception on /get_graph_data [GET]\n",
      "Traceback (most recent call last):\n",
      "  File \"C:\\Users\\Laverne\\anaconda3\\lib\\site-packages\\flask\\app.py\", line 2525, in wsgi_app\n",
      "    response = self.full_dispatch_request()\n",
      "  File \"C:\\Users\\Laverne\\anaconda3\\lib\\site-packages\\flask\\app.py\", line 1822, in full_dispatch_request\n",
      "    rv = self.handle_user_exception(e)\n",
      "  File \"C:\\Users\\Laverne\\anaconda3\\lib\\site-packages\\flask\\app.py\", line 1820, in full_dispatch_request\n",
      "    rv = self.dispatch_request()\n",
      "  File \"C:\\Users\\Laverne\\anaconda3\\lib\\site-packages\\flask\\app.py\", line 1796, in dispatch_request\n",
      "    return self.ensure_sync(self.view_functions[rule.endpoint])(**view_args)\n",
      "  File \"C:\\Users\\Laverne\\AppData\\Local\\Temp\\ipykernel_16992\\1007073488.py\", line 399, in get_graph_data\n",
      "    return jsonify({'graph_src': f'static/graph.jpg?{timestamp}'})\n",
      "NameError: name 'jsonify' is not defined\n",
      "127.0.0.1 - - [20/Jul/2023 22:45:41] \"GET /get_graph_data HTTP/1.1\" 500 -\n",
      "[2023-07-20 22:45:43,202] ERROR in app: Exception on /get_hist [GET]\n",
      "Traceback (most recent call last):\n",
      "  File \"C:\\Users\\Laverne\\anaconda3\\lib\\site-packages\\flask\\app.py\", line 2525, in wsgi_app\n",
      "    response = self.full_dispatch_request()\n",
      "  File \"C:\\Users\\Laverne\\anaconda3\\lib\\site-packages\\flask\\app.py\", line 1822, in full_dispatch_request\n",
      "    rv = self.handle_user_exception(e)\n",
      "  File \"C:\\Users\\Laverne\\anaconda3\\lib\\site-packages\\flask\\app.py\", line 1820, in full_dispatch_request\n",
      "    rv = self.dispatch_request()\n",
      "  File \"C:\\Users\\Laverne\\anaconda3\\lib\\site-packages\\flask\\app.py\", line 1796, in dispatch_request\n",
      "    return self.ensure_sync(self.view_functions[rule.endpoint])(**view_args)\n",
      "  File \"C:\\Users\\Laverne\\AppData\\Local\\Temp\\ipykernel_16992\\1007073488.py\", line 416, in get_hist\n",
      "    return jsonify({'hist_src': f'static/histogram.jpg?{timestamp}'})\n",
      "NameError: name 'jsonify' is not defined\n",
      "127.0.0.1 - - [20/Jul/2023 22:45:43] \"GET /get_hist HTTP/1.1\" 500 -\n",
      "[2023-07-20 22:45:43,231] ERROR in app: Exception on /get_hist [GET]\n",
      "Traceback (most recent call last):\n",
      "  File \"C:\\Users\\Laverne\\anaconda3\\lib\\site-packages\\flask\\app.py\", line 2525, in wsgi_app\n",
      "    response = self.full_dispatch_request()\n",
      "  File \"C:\\Users\\Laverne\\anaconda3\\lib\\site-packages\\flask\\app.py\", line 1822, in full_dispatch_request\n",
      "    rv = self.handle_user_exception(e)\n",
      "  File \"C:\\Users\\Laverne\\anaconda3\\lib\\site-packages\\flask\\app.py\", line 1820, in full_dispatch_request\n",
      "    rv = self.dispatch_request()\n",
      "  File \"C:\\Users\\Laverne\\anaconda3\\lib\\site-packages\\flask\\app.py\", line 1796, in dispatch_request\n",
      "    return self.ensure_sync(self.view_functions[rule.endpoint])(**view_args)\n",
      "  File \"C:\\Users\\Laverne\\AppData\\Local\\Temp\\ipykernel_16992\\1007073488.py\", line 416, in get_hist\n",
      "    return jsonify({'hist_src': f'static/histogram.jpg?{timestamp}'})\n",
      "NameError: name 'jsonify' is not defined\n",
      "127.0.0.1 - - [20/Jul/2023 22:45:43] \"GET /get_hist HTTP/1.1\" 500 -\n",
      "[2023-07-20 22:45:44,204] ERROR in app: Exception on /get_graph_data [GET]\n",
      "Traceback (most recent call last):\n",
      "  File \"C:\\Users\\Laverne\\anaconda3\\lib\\site-packages\\flask\\app.py\", line 2525, in wsgi_app\n",
      "    response = self.full_dispatch_request()\n",
      "  File \"C:\\Users\\Laverne\\anaconda3\\lib\\site-packages\\flask\\app.py\", line 1822, in full_dispatch_request\n",
      "    rv = self.handle_user_exception(e)\n",
      "  File \"C:\\Users\\Laverne\\anaconda3\\lib\\site-packages\\flask\\app.py\", line 1820, in full_dispatch_request\n",
      "    rv = self.dispatch_request()\n",
      "  File \"C:\\Users\\Laverne\\anaconda3\\lib\\site-packages\\flask\\app.py\", line 1796, in dispatch_request\n",
      "    return self.ensure_sync(self.view_functions[rule.endpoint])(**view_args)\n",
      "  File \"C:\\Users\\Laverne\\AppData\\Local\\Temp\\ipykernel_16992\\1007073488.py\", line 399, in get_graph_data\n",
      "    return jsonify({'graph_src': f'static/graph.jpg?{timestamp}'})\n",
      "NameError: name 'jsonify' is not defined\n",
      "127.0.0.1 - - [20/Jul/2023 22:45:44] \"GET /get_graph_data HTTP/1.1\" 500 -\n",
      "[2023-07-20 22:45:47,212] ERROR in app: Exception on /get_graph_data [GET]\n",
      "Traceback (most recent call last):\n",
      "  File \"C:\\Users\\Laverne\\anaconda3\\lib\\site-packages\\flask\\app.py\", line 2525, in wsgi_app\n",
      "    response = self.full_dispatch_request()\n",
      "  File \"C:\\Users\\Laverne\\anaconda3\\lib\\site-packages\\flask\\app.py\", line 1822, in full_dispatch_request\n",
      "    rv = self.handle_user_exception(e)\n",
      "  File \"C:\\Users\\Laverne\\anaconda3\\lib\\site-packages\\flask\\app.py\", line 1820, in full_dispatch_request\n",
      "    rv = self.dispatch_request()\n",
      "  File \"C:\\Users\\Laverne\\anaconda3\\lib\\site-packages\\flask\\app.py\", line 1796, in dispatch_request\n",
      "    return self.ensure_sync(self.view_functions[rule.endpoint])(**view_args)\n",
      "  File \"C:\\Users\\Laverne\\AppData\\Local\\Temp\\ipykernel_16992\\1007073488.py\", line 399, in get_graph_data\n",
      "    return jsonify({'graph_src': f'static/graph.jpg?{timestamp}'})\n",
      "NameError: name 'jsonify' is not defined\n",
      "127.0.0.1 - - [20/Jul/2023 22:45:47] \"GET /get_graph_data HTTP/1.1\" 500 -\n",
      "[2023-07-20 22:45:48,209] ERROR in app: Exception on /get_hist [GET]\n",
      "Traceback (most recent call last):\n",
      "  File \"C:\\Users\\Laverne\\anaconda3\\lib\\site-packages\\flask\\app.py\", line 2525, in wsgi_app\n",
      "    response = self.full_dispatch_request()\n",
      "  File \"C:\\Users\\Laverne\\anaconda3\\lib\\site-packages\\flask\\app.py\", line 1822, in full_dispatch_request\n",
      "    rv = self.handle_user_exception(e)\n",
      "  File \"C:\\Users\\Laverne\\anaconda3\\lib\\site-packages\\flask\\app.py\", line 1820, in full_dispatch_request\n",
      "    rv = self.dispatch_request()\n",
      "  File \"C:\\Users\\Laverne\\anaconda3\\lib\\site-packages\\flask\\app.py\", line 1796, in dispatch_request\n",
      "    return self.ensure_sync(self.view_functions[rule.endpoint])(**view_args)\n",
      "  File \"C:\\Users\\Laverne\\AppData\\Local\\Temp\\ipykernel_16992\\1007073488.py\", line 416, in get_hist\n",
      "    return jsonify({'hist_src': f'static/histogram.jpg?{timestamp}'})\n",
      "NameError: name 'jsonify' is not defined\n"
     ]
    },
    {
     "name": "stderr",
     "output_type": "stream",
     "text": [
      "127.0.0.1 - - [20/Jul/2023 22:45:48] \"GET /get_hist HTTP/1.1\" 500 -\n",
      "[2023-07-20 22:45:48,243] ERROR in app: Exception on /get_hist [GET]\n",
      "Traceback (most recent call last):\n",
      "  File \"C:\\Users\\Laverne\\anaconda3\\lib\\site-packages\\flask\\app.py\", line 2525, in wsgi_app\n",
      "    response = self.full_dispatch_request()\n",
      "  File \"C:\\Users\\Laverne\\anaconda3\\lib\\site-packages\\flask\\app.py\", line 1822, in full_dispatch_request\n",
      "    rv = self.handle_user_exception(e)\n",
      "  File \"C:\\Users\\Laverne\\anaconda3\\lib\\site-packages\\flask\\app.py\", line 1820, in full_dispatch_request\n",
      "    rv = self.dispatch_request()\n",
      "  File \"C:\\Users\\Laverne\\anaconda3\\lib\\site-packages\\flask\\app.py\", line 1796, in dispatch_request\n",
      "    return self.ensure_sync(self.view_functions[rule.endpoint])(**view_args)\n",
      "  File \"C:\\Users\\Laverne\\AppData\\Local\\Temp\\ipykernel_16992\\1007073488.py\", line 416, in get_hist\n",
      "    return jsonify({'hist_src': f'static/histogram.jpg?{timestamp}'})\n",
      "NameError: name 'jsonify' is not defined\n",
      "127.0.0.1 - - [20/Jul/2023 22:45:48] \"GET /get_hist HTTP/1.1\" 500 -\n",
      "[2023-07-20 22:45:50,203] ERROR in app: Exception on /get_graph_data [GET]\n",
      "Traceback (most recent call last):\n",
      "  File \"C:\\Users\\Laverne\\anaconda3\\lib\\site-packages\\flask\\app.py\", line 2525, in wsgi_app\n",
      "    response = self.full_dispatch_request()\n",
      "  File \"C:\\Users\\Laverne\\anaconda3\\lib\\site-packages\\flask\\app.py\", line 1822, in full_dispatch_request\n",
      "    rv = self.handle_user_exception(e)\n",
      "  File \"C:\\Users\\Laverne\\anaconda3\\lib\\site-packages\\flask\\app.py\", line 1820, in full_dispatch_request\n",
      "    rv = self.dispatch_request()\n",
      "  File \"C:\\Users\\Laverne\\anaconda3\\lib\\site-packages\\flask\\app.py\", line 1796, in dispatch_request\n",
      "    return self.ensure_sync(self.view_functions[rule.endpoint])(**view_args)\n",
      "  File \"C:\\Users\\Laverne\\AppData\\Local\\Temp\\ipykernel_16992\\1007073488.py\", line 399, in get_graph_data\n",
      "    return jsonify({'graph_src': f'static/graph.jpg?{timestamp}'})\n",
      "NameError: name 'jsonify' is not defined\n",
      "127.0.0.1 - - [20/Jul/2023 22:45:50] \"GET /get_graph_data HTTP/1.1\" 500 -\n",
      "[2023-07-20 22:45:53,212] ERROR in app: Exception on /get_graph_data [GET]\n",
      "Traceback (most recent call last):\n",
      "  File \"C:\\Users\\Laverne\\anaconda3\\lib\\site-packages\\flask\\app.py\", line 2525, in wsgi_app\n",
      "    response = self.full_dispatch_request()\n",
      "  File \"C:\\Users\\Laverne\\anaconda3\\lib\\site-packages\\flask\\app.py\", line 1822, in full_dispatch_request\n",
      "    rv = self.handle_user_exception(e)\n",
      "  File \"C:\\Users\\Laverne\\anaconda3\\lib\\site-packages\\flask\\app.py\", line 1820, in full_dispatch_request\n",
      "    rv = self.dispatch_request()\n",
      "  File \"C:\\Users\\Laverne\\anaconda3\\lib\\site-packages\\flask\\app.py\", line 1796, in dispatch_request\n",
      "    return self.ensure_sync(self.view_functions[rule.endpoint])(**view_args)\n",
      "  File \"C:\\Users\\Laverne\\AppData\\Local\\Temp\\ipykernel_16992\\1007073488.py\", line 399, in get_graph_data\n",
      "    return jsonify({'graph_src': f'static/graph.jpg?{timestamp}'})\n",
      "NameError: name 'jsonify' is not defined\n",
      "127.0.0.1 - - [20/Jul/2023 22:45:53] \"GET /get_graph_data HTTP/1.1[2023-07-20 22:45:53,219] ERROR in app: Exception on /get_hist [GET]\n",
      "Traceback (most recent call last):\n",
      "  File \"C:\\Users\\Laverne\\anaconda3\\lib\\site-packages\\flask\\app.py\", line 2525, in wsgi_app\n",
      "    response = self.full_dispatch_request()\n",
      "  File \"C:\\Users\\Laverne\\anaconda3\\lib\\site-packages\\flask\\app.py\", line 1822, in full_dispatch_request\n",
      "    rv = self.handle_user_exception(e)\n",
      "  File \"C:\\Users\\Laverne\\anaconda3\\lib\\site-packages\\flask\\app.py\", line 1820, in full_dispatch_request\n",
      "    rv = self.dispatch_request()\n",
      "  File \"C:\\Users\\Laverne\\anaconda3\\lib\\site-packages\\flask\\app.py\", line 1796, in dispatch_request\n",
      "    return self.ensure_sync(self.view_functions[rule.endpoint])(**view_args)\n",
      "  File \"C:\\Users\\Laverne\\AppData\\Local\\Temp\\ipykernel_16992\\1007073488.py\", line 416, in get_hist\n",
      "    return jsonify({'hist_src': f'static/histogram.jpg?{timestamp}'})\n",
      "NameError: name 'jsonify' is not defined\n",
      "\" 500 -\n",
      "127.0.0.1 - - [20/Jul/2023 22:45:53] \"GET /get_hist HTTP/1.1\" 500 -\n",
      "[2023-07-20 22:45:53,274] ERROR in app: Exception on /get_hist [GET]\n",
      "Traceback (most recent call last):\n",
      "  File \"C:\\Users\\Laverne\\anaconda3\\lib\\site-packages\\flask\\app.py\", line 2525, in wsgi_app\n",
      "    response = self.full_dispatch_request()\n",
      "  File \"C:\\Users\\Laverne\\anaconda3\\lib\\site-packages\\flask\\app.py\", line 1822, in full_dispatch_request\n",
      "    rv = self.handle_user_exception(e)\n",
      "  File \"C:\\Users\\Laverne\\anaconda3\\lib\\site-packages\\flask\\app.py\", line 1820, in full_dispatch_request\n",
      "    rv = self.dispatch_request()\n",
      "  File \"C:\\Users\\Laverne\\anaconda3\\lib\\site-packages\\flask\\app.py\", line 1796, in dispatch_request\n",
      "    return self.ensure_sync(self.view_functions[rule.endpoint])(**view_args)\n",
      "  File \"C:\\Users\\Laverne\\AppData\\Local\\Temp\\ipykernel_16992\\1007073488.py\", line 416, in get_hist\n",
      "    return jsonify({'hist_src': f'static/histogram.jpg?{timestamp}'})\n",
      "NameError: name 'jsonify' is not defined\n",
      "127.0.0.1 - - [20/Jul/2023 22:45:53] \"GET /get_hist HTTP/1.1\" 500 -\n",
      "[2023-07-20 22:45:56,208] ERROR in app: Exception on /get_graph_data [GET]\n",
      "Traceback (most recent call last):\n",
      "  File \"C:\\Users\\Laverne\\anaconda3\\lib\\site-packages\\flask\\app.py\", line 2525, in wsgi_app\n",
      "    response = self.full_dispatch_request()\n",
      "  File \"C:\\Users\\Laverne\\anaconda3\\lib\\site-packages\\flask\\app.py\", line 1822, in full_dispatch_request\n",
      "    rv = self.handle_user_exception(e)\n",
      "  File \"C:\\Users\\Laverne\\anaconda3\\lib\\site-packages\\flask\\app.py\", line 1820, in full_dispatch_request\n",
      "    rv = self.dispatch_request()\n",
      "  File \"C:\\Users\\Laverne\\anaconda3\\lib\\site-packages\\flask\\app.py\", line 1796, in dispatch_request\n",
      "    return self.ensure_sync(self.view_functions[rule.endpoint])(**view_args)\n",
      "  File \"C:\\Users\\Laverne\\AppData\\Local\\Temp\\ipykernel_16992\\1007073488.py\", line 399, in get_graph_data\n",
      "    return jsonify({'graph_src': f'static/graph.jpg?{timestamp}'})\n",
      "NameError: name 'jsonify' is not defined\n",
      "127.0.0.1 - - [20/Jul/2023 22:45:56] \"GET /get_graph_data HTTP/1.1\" 500 -\n",
      "[2023-07-20 22:45:58,210] ERROR in app: Exception on /get_hist [GET]\n",
      "Traceback (most recent call last):\n",
      "  File \"C:\\Users\\Laverne\\anaconda3\\lib\\site-packages\\flask\\app.py\", line 2525, in wsgi_app\n",
      "    response = self.full_dispatch_request()\n",
      "  File \"C:\\Users\\Laverne\\anaconda3\\lib\\site-packages\\flask\\app.py\", line 1822, in full_dispatch_request\n",
      "    rv = self.handle_user_exception(e)\n",
      "  File \"C:\\Users\\Laverne\\anaconda3\\lib\\site-packages\\flask\\app.py\", line 1820, in full_dispatch_request\n",
      "    rv = self.dispatch_request()\n",
      "  File \"C:\\Users\\Laverne\\anaconda3\\lib\\site-packages\\flask\\app.py\", line 1796, in dispatch_request\n",
      "    return self.ensure_sync(self.view_functions[rule.endpoint])(**view_args)\n",
      "  File \"C:\\Users\\Laverne\\AppData\\Local\\Temp\\ipykernel_16992\\1007073488.py\", line 416, in get_hist\n",
      "    return jsonify({'hist_src': f'static/histogram.jpg?{timestamp}'})\n",
      "NameError: name 'jsonify' is not defined\n",
      "127.0.0.1 - - [20/Jul/2023 22:45:58] \"GET /get_hist HTTP/1.1\" 500 -\n",
      "[2023-07-20 22:45:58,238] ERROR in app: Exception on /get_hist [GET]\n",
      "Traceback (most recent call last):\n",
      "  File \"C:\\Users\\Laverne\\anaconda3\\lib\\site-packages\\flask\\app.py\", line 2525, in wsgi_app\n",
      "    response = self.full_dispatch_request()\n",
      "  File \"C:\\Users\\Laverne\\anaconda3\\lib\\site-packages\\flask\\app.py\", line 1822, in full_dispatch_request\n",
      "    rv = self.handle_user_exception(e)\n",
      "  File \"C:\\Users\\Laverne\\anaconda3\\lib\\site-packages\\flask\\app.py\", line 1820, in full_dispatch_request\n",
      "    rv = self.dispatch_request()\n",
      "  File \"C:\\Users\\Laverne\\anaconda3\\lib\\site-packages\\flask\\app.py\", line 1796, in dispatch_request\n",
      "    return self.ensure_sync(self.view_functions[rule.endpoint])(**view_args)\n",
      "  File \"C:\\Users\\Laverne\\AppData\\Local\\Temp\\ipykernel_16992\\1007073488.py\", line 416, in get_hist\n",
      "    return jsonify({'hist_src': f'static/histogram.jpg?{timestamp}'})\n",
      "NameError: name 'jsonify' is not defined\n",
      "127.0.0.1 - - [20/Jul/2023 22:45:58] \"GET /get_hist HTTP/1.1\" 500 -\n",
      "[2023-07-20 22:45:59,212] ERROR in app: Exception on /get_graph_data [GET]\n",
      "Traceback (most recent call last):\n",
      "  File \"C:\\Users\\Laverne\\anaconda3\\lib\\site-packages\\flask\\app.py\", line 2525, in wsgi_app\n",
      "    response = self.full_dispatch_request()\n",
      "  File \"C:\\Users\\Laverne\\anaconda3\\lib\\site-packages\\flask\\app.py\", line 1822, in full_dispatch_request\n",
      "    rv = self.handle_user_exception(e)\n",
      "  File \"C:\\Users\\Laverne\\anaconda3\\lib\\site-packages\\flask\\app.py\", line 1820, in full_dispatch_request\n",
      "    rv = self.dispatch_request()\n",
      "  File \"C:\\Users\\Laverne\\anaconda3\\lib\\site-packages\\flask\\app.py\", line 1796, in dispatch_request\n",
      "    return self.ensure_sync(self.view_functions[rule.endpoint])(**view_args)\n",
      "  File \"C:\\Users\\Laverne\\AppData\\Local\\Temp\\ipykernel_16992\\1007073488.py\", line 399, in get_graph_data\n",
      "    return jsonify({'graph_src': f'static/graph.jpg?{timestamp}'})\n",
      "NameError: name 'jsonify' is not defined\n"
     ]
    },
    {
     "name": "stderr",
     "output_type": "stream",
     "text": [
      "127.0.0.1 - - [20/Jul/2023 22:45:59] \"GET /get_graph_data HTTP/1.1\" 500 -\n",
      "[2023-07-20 22:46:02,203] ERROR in app: Exception on /get_graph_data [GET]\n",
      "Traceback (most recent call last):\n",
      "  File \"C:\\Users\\Laverne\\anaconda3\\lib\\site-packages\\flask\\app.py\", line 2525, in wsgi_app\n",
      "    response = self.full_dispatch_request()\n",
      "  File \"C:\\Users\\Laverne\\anaconda3\\lib\\site-packages\\flask\\app.py\", line 1822, in full_dispatch_request\n",
      "    rv = self.handle_user_exception(e)\n",
      "  File \"C:\\Users\\Laverne\\anaconda3\\lib\\site-packages\\flask\\app.py\", line 1820, in full_dispatch_request\n",
      "    rv = self.dispatch_request()\n",
      "  File \"C:\\Users\\Laverne\\anaconda3\\lib\\site-packages\\flask\\app.py\", line 1796, in dispatch_request\n",
      "    return self.ensure_sync(self.view_functions[rule.endpoint])(**view_args)\n",
      "  File \"C:\\Users\\Laverne\\AppData\\Local\\Temp\\ipykernel_16992\\1007073488.py\", line 399, in get_graph_data\n",
      "    return jsonify({'graph_src': f'static/graph.jpg?{timestamp}'})\n",
      "NameError: name 'jsonify' is not defined\n",
      "127.0.0.1 - - [20/Jul/2023 22:46:02] \"GET /get_graph_data HTTP/1.1\" 500 -\n",
      "[2023-07-20 22:46:03,208] ERROR in app: Exception on /get_hist [GET]\n",
      "Traceback (most recent call last):\n",
      "  File \"C:\\Users\\Laverne\\anaconda3\\lib\\site-packages\\flask\\app.py\", line 2525, in wsgi_app\n",
      "    response = self.full_dispatch_request()\n",
      "  File \"C:\\Users\\Laverne\\anaconda3\\lib\\site-packages\\flask\\app.py\", line 1822, in full_dispatch_request\n",
      "    rv = self.handle_user_exception(e)\n",
      "  File \"C:\\Users\\Laverne\\anaconda3\\lib\\site-packages\\flask\\app.py\", line 1820, in full_dispatch_request\n",
      "    rv = self.dispatch_request()\n",
      "  File \"C:\\Users\\Laverne\\anaconda3\\lib\\site-packages\\flask\\app.py\", line 1796, in dispatch_request\n",
      "    return self.ensure_sync(self.view_functions[rule.endpoint])(**view_args)\n",
      "  File \"C:\\Users\\Laverne\\AppData\\Local\\Temp\\ipykernel_16992\\1007073488.py\", line 416, in get_hist\n",
      "    return jsonify({'hist_src': f'static/histogram.jpg?{timestamp}'})\n",
      "NameError: name 'jsonify' is not defined\n",
      "127.0.0.1 - - [20/Jul/2023 22:46:03] \"GET /get_hist HTTP/1.1\" 500 -\n",
      "[2023-07-20 22:46:03,236] ERROR in app: Exception on /get_hist [GET]\n",
      "Traceback (most recent call last):\n",
      "  File \"C:\\Users\\Laverne\\anaconda3\\lib\\site-packages\\flask\\app.py\", line 2525, in wsgi_app\n",
      "    response = self.full_dispatch_request()\n",
      "  File \"C:\\Users\\Laverne\\anaconda3\\lib\\site-packages\\flask\\app.py\", line 1822, in full_dispatch_request\n",
      "    rv = self.handle_user_exception(e)\n",
      "  File \"C:\\Users\\Laverne\\anaconda3\\lib\\site-packages\\flask\\app.py\", line 1820, in full_dispatch_request\n",
      "    rv = self.dispatch_request()\n",
      "  File \"C:\\Users\\Laverne\\anaconda3\\lib\\site-packages\\flask\\app.py\", line 1796, in dispatch_request\n",
      "    return self.ensure_sync(self.view_functions[rule.endpoint])(**view_args)\n",
      "  File \"C:\\Users\\Laverne\\AppData\\Local\\Temp\\ipykernel_16992\\1007073488.py\", line 416, in get_hist\n",
      "    return jsonify({'hist_src': f'static/histogram.jpg?{timestamp}'})\n",
      "NameError: name 'jsonify' is not defined\n",
      "127.0.0.1 - - [20/Jul/2023 22:46:03] \"GET /get_hist HTTP/1.1\" 500 -\n",
      "[2023-07-20 22:46:05,203] ERROR in app: Exception on /get_graph_data [GET]\n",
      "Traceback (most recent call last):\n",
      "  File \"C:\\Users\\Laverne\\anaconda3\\lib\\site-packages\\flask\\app.py\", line 2525, in wsgi_app\n",
      "    response = self.full_dispatch_request()\n",
      "  File \"C:\\Users\\Laverne\\anaconda3\\lib\\site-packages\\flask\\app.py\", line 1822, in full_dispatch_request\n",
      "    rv = self.handle_user_exception(e)\n",
      "  File \"C:\\Users\\Laverne\\anaconda3\\lib\\site-packages\\flask\\app.py\", line 1820, in full_dispatch_request\n",
      "    rv = self.dispatch_request()\n",
      "  File \"C:\\Users\\Laverne\\anaconda3\\lib\\site-packages\\flask\\app.py\", line 1796, in dispatch_request\n",
      "    return self.ensure_sync(self.view_functions[rule.endpoint])(**view_args)\n",
      "  File \"C:\\Users\\Laverne\\AppData\\Local\\Temp\\ipykernel_16992\\1007073488.py\", line 399, in get_graph_data\n",
      "    return jsonify({'graph_src': f'static/graph.jpg?{timestamp}'})\n",
      "NameError: name 'jsonify' is not defined\n",
      "127.0.0.1 - - [20/Jul/2023 22:46:05] \"GET /get_graph_data HTTP/1.1\" 500 -\n",
      "[2023-07-20 22:46:08,211] ERROR in app: Exception on /get_graph_data [GET]\n",
      "Traceback (most recent call last):\n",
      "  File \"C:\\Users\\Laverne\\anaconda3\\lib\\site-packages\\flask\\app.py\", line 2525, in wsgi_app\n",
      "    response = self.full_dispatch_request()\n",
      "  File \"C:\\Users\\Laverne\\anaconda3\\lib\\site-packages\\flask\\app.py\", line 1822, in full_dispatch_request\n",
      "    rv = self.handle_user_exception(e)\n",
      "  File \"C:\\Users\\Laverne\\anaconda3\\lib\\site-packages\\flask\\app.py\", line 1820, in full_dispatch_request\n",
      "    rv = self.dispatch_request()\n",
      "  File \"C:\\Users\\Laverne\\anaconda3\\lib\\site-packages\\flask\\app.py\", line 1796, in dispatch_request\n",
      "    return self.ensure_sync(self.view_functions[rule.endpoint])(**view_args)\n",
      "  File \"C:\\Users\\Laverne\\AppData\\Local\\Temp\\ipykernel_16992\\1007073488.py\", line 399, in get_graph_data\n",
      "    return jsonify({'graph_src': f'static/graph.jpg?{timestamp}'})\n",
      "NameError: name 'jsonify' is not defined\n",
      "127.0.0.1 - - [20/Jul/2023 22:46:08] \"[2023-07-20 22:46:08,225] ERROR in app: Exception on /get_hist [GET]\n",
      "Traceback (most recent call last):\n",
      "  File \"C:\\Users\\Laverne\\anaconda3\\lib\\site-packages\\flask\\app.py\", line 2525, in wsgi_app\n",
      "    response = self.full_dispatch_request()\n",
      "  File \"C:\\Users\\Laverne\\anaconda3\\lib\\site-packages\\flask\\app.py\", line 1822, in full_dispatch_request\n",
      "    rv = self.handle_user_exception(e)\n",
      "  File \"C:\\Users\\Laverne\\anaconda3\\lib\\site-packages\\flask\\app.py\", line 1820, in full_dispatch_request\n",
      "    rv = self.dispatch_request()\n",
      "  File \"C:\\Users\\Laverne\\anaconda3\\lib\\site-packages\\flask\\app.py\", line 1796, in dispatch_request\n",
      "    return self.ensure_sync(self.view_functions[rule.endpoint])(**view_args)\n",
      "  File \"C:\\Users\\Laverne\\AppData\\Local\\Temp\\ipykernel_16992\\1007073488.py\", line 416, in get_hist\n",
      "    return jsonify({'hist_src': f'static/histogram.jpg?{timestamp}'})\n",
      "NameError: name 'jsonify' is not defined\n",
      "GET /get_graph_data HTTP/1.1\" 500 -\n",
      "127.0.0.1 - - [20/Jul/2023 22:46:08] \"GET /get_hist HTTP/1.1\" 500 -\n",
      "[2023-07-20 22:46:08,272] ERROR in app: Exception on /get_hist [GET]\n",
      "Traceback (most recent call last):\n",
      "  File \"C:\\Users\\Laverne\\anaconda3\\lib\\site-packages\\flask\\app.py\", line 2525, in wsgi_app\n",
      "    response = self.full_dispatch_request()\n",
      "  File \"C:\\Users\\Laverne\\anaconda3\\lib\\site-packages\\flask\\app.py\", line 1822, in full_dispatch_request\n",
      "    rv = self.handle_user_exception(e)\n",
      "  File \"C:\\Users\\Laverne\\anaconda3\\lib\\site-packages\\flask\\app.py\", line 1820, in full_dispatch_request\n",
      "    rv = self.dispatch_request()\n",
      "  File \"C:\\Users\\Laverne\\anaconda3\\lib\\site-packages\\flask\\app.py\", line 1796, in dispatch_request\n",
      "    return self.ensure_sync(self.view_functions[rule.endpoint])(**view_args)\n",
      "  File \"C:\\Users\\Laverne\\AppData\\Local\\Temp\\ipykernel_16992\\1007073488.py\", line 416, in get_hist\n",
      "    return jsonify({'hist_src': f'static/histogram.jpg?{timestamp}'})\n",
      "NameError: name 'jsonify' is not defined\n",
      "127.0.0.1 - - [20/Jul/2023 22:46:08] \"GET /get_hist HTTP/1.1\" 500 -\n",
      "[2023-07-20 22:46:11,203] ERROR in app: Exception on /get_graph_data [GET]\n",
      "Traceback (most recent call last):\n",
      "  File \"C:\\Users\\Laverne\\anaconda3\\lib\\site-packages\\flask\\app.py\", line 2525, in wsgi_app\n",
      "    response = self.full_dispatch_request()\n",
      "  File \"C:\\Users\\Laverne\\anaconda3\\lib\\site-packages\\flask\\app.py\", line 1822, in full_dispatch_request\n",
      "    rv = self.handle_user_exception(e)\n",
      "  File \"C:\\Users\\Laverne\\anaconda3\\lib\\site-packages\\flask\\app.py\", line 1820, in full_dispatch_request\n",
      "    rv = self.dispatch_request()\n",
      "  File \"C:\\Users\\Laverne\\anaconda3\\lib\\site-packages\\flask\\app.py\", line 1796, in dispatch_request\n",
      "    return self.ensure_sync(self.view_functions[rule.endpoint])(**view_args)\n",
      "  File \"C:\\Users\\Laverne\\AppData\\Local\\Temp\\ipykernel_16992\\1007073488.py\", line 399, in get_graph_data\n",
      "    return jsonify({'graph_src': f'static/graph.jpg?{timestamp}'})\n",
      "NameError: name 'jsonify' is not defined\n",
      "127.0.0.1 - - [20/Jul/2023 22:46:11] \"GET /get_graph_data HTTP/1.1\" 500 -\n",
      "[2023-07-20 22:46:13,207] ERROR in app: Exception on /get_hist [GET]\n",
      "Traceback (most recent call last):\n",
      "  File \"C:\\Users\\Laverne\\anaconda3\\lib\\site-packages\\flask\\app.py\", line 2525, in wsgi_app\n",
      "    response = self.full_dispatch_request()\n",
      "  File \"C:\\Users\\Laverne\\anaconda3\\lib\\site-packages\\flask\\app.py\", line 1822, in full_dispatch_request\n",
      "    rv = self.handle_user_exception(e)\n",
      "  File \"C:\\Users\\Laverne\\anaconda3\\lib\\site-packages\\flask\\app.py\", line 1820, in full_dispatch_request\n",
      "    rv = self.dispatch_request()\n",
      "  File \"C:\\Users\\Laverne\\anaconda3\\lib\\site-packages\\flask\\app.py\", line 1796, in dispatch_request\n",
      "    return self.ensure_sync(self.view_functions[rule.endpoint])(**view_args)\n",
      "  File \"C:\\Users\\Laverne\\AppData\\Local\\Temp\\ipykernel_16992\\1007073488.py\", line 416, in get_hist\n",
      "    return jsonify({'hist_src': f'static/histogram.jpg?{timestamp}'})\n",
      "NameError: name 'jsonify' is not defined\n"
     ]
    },
    {
     "name": "stderr",
     "output_type": "stream",
     "text": [
      "127.0.0.1 - - [20/Jul/2023 22:46:13] \"GET /get_hist HTTP/1.1\" 500 -\n",
      "[2023-07-20 22:46:13,230] ERROR in app: Exception on /get_hist [GET]\n",
      "Traceback (most recent call last):\n",
      "  File \"C:\\Users\\Laverne\\anaconda3\\lib\\site-packages\\flask\\app.py\", line 2525, in wsgi_app\n",
      "    response = self.full_dispatch_request()\n",
      "  File \"C:\\Users\\Laverne\\anaconda3\\lib\\site-packages\\flask\\app.py\", line 1822, in full_dispatch_request\n",
      "    rv = self.handle_user_exception(e)\n",
      "  File \"C:\\Users\\Laverne\\anaconda3\\lib\\site-packages\\flask\\app.py\", line 1820, in full_dispatch_request\n",
      "    rv = self.dispatch_request()\n",
      "  File \"C:\\Users\\Laverne\\anaconda3\\lib\\site-packages\\flask\\app.py\", line 1796, in dispatch_request\n",
      "    return self.ensure_sync(self.view_functions[rule.endpoint])(**view_args)\n",
      "  File \"C:\\Users\\Laverne\\AppData\\Local\\Temp\\ipykernel_16992\\1007073488.py\", line 416, in get_hist\n",
      "    return jsonify({'hist_src': f'static/histogram.jpg?{timestamp}'})\n",
      "NameError: name 'jsonify' is not defined\n",
      "127.0.0.1 - - [20/Jul/2023 22:46:13] \"GET /get_hist HTTP/1.1\" 500 -\n",
      "[2023-07-20 22:46:14,207] ERROR in app: Exception on /get_graph_data [GET]\n",
      "Traceback (most recent call last):\n",
      "  File \"C:\\Users\\Laverne\\anaconda3\\lib\\site-packages\\flask\\app.py\", line 2525, in wsgi_app\n",
      "    response = self.full_dispatch_request()\n",
      "  File \"C:\\Users\\Laverne\\anaconda3\\lib\\site-packages\\flask\\app.py\", line 1822, in full_dispatch_request\n",
      "    rv = self.handle_user_exception(e)\n",
      "  File \"C:\\Users\\Laverne\\anaconda3\\lib\\site-packages\\flask\\app.py\", line 1820, in full_dispatch_request\n",
      "    rv = self.dispatch_request()\n",
      "  File \"C:\\Users\\Laverne\\anaconda3\\lib\\site-packages\\flask\\app.py\", line 1796, in dispatch_request\n",
      "    return self.ensure_sync(self.view_functions[rule.endpoint])(**view_args)\n",
      "  File \"C:\\Users\\Laverne\\AppData\\Local\\Temp\\ipykernel_16992\\1007073488.py\", line 399, in get_graph_data\n",
      "    return jsonify({'graph_src': f'static/graph.jpg?{timestamp}'})\n",
      "NameError: name 'jsonify' is not defined\n",
      "127.0.0.1 - - [20/Jul/2023 22:46:14] \"GET /get_graph_data HTTP/1.1\" 500 -\n",
      "[2023-07-20 22:46:17,207] ERROR in app: Exception on /get_graph_data [GET]\n",
      "Traceback (most recent call last):\n",
      "  File \"C:\\Users\\Laverne\\anaconda3\\lib\\site-packages\\flask\\app.py\", line 2525, in wsgi_app\n",
      "    response = self.full_dispatch_request()\n",
      "  File \"C:\\Users\\Laverne\\anaconda3\\lib\\site-packages\\flask\\app.py\", line 1822, in full_dispatch_request\n",
      "    rv = self.handle_user_exception(e)\n",
      "  File \"C:\\Users\\Laverne\\anaconda3\\lib\\site-packages\\flask\\app.py\", line 1820, in full_dispatch_request\n",
      "    rv = self.dispatch_request()\n",
      "  File \"C:\\Users\\Laverne\\anaconda3\\lib\\site-packages\\flask\\app.py\", line 1796, in dispatch_request\n",
      "    return self.ensure_sync(self.view_functions[rule.endpoint])(**view_args)\n",
      "  File \"C:\\Users\\Laverne\\AppData\\Local\\Temp\\ipykernel_16992\\1007073488.py\", line 399, in get_graph_data\n",
      "    return jsonify({'graph_src': f'static/graph.jpg?{timestamp}'})\n",
      "NameError: name 'jsonify' is not defined\n",
      "127.0.0.1 - - [20/Jul/2023 22:46:17] \"GET /get_graph_data HTTP/1.1\" 500 -\n",
      "[2023-07-20 22:46:18,213] ERROR in app: Exception on /get_hist [GET]\n",
      "Traceback (most recent call last):\n",
      "  File \"C:\\Users\\Laverne\\anaconda3\\lib\\site-packages\\flask\\app.py\", line 2525, in wsgi_app\n",
      "    response = self.full_dispatch_request()\n",
      "  File \"C:\\Users\\Laverne\\anaconda3\\lib\\site-packages\\flask\\app.py\", line 1822, in full_dispatch_request\n",
      "    rv = self.handle_user_exception(e)\n",
      "  File \"C:\\Users\\Laverne\\anaconda3\\lib\\site-packages\\flask\\app.py\", line 1820, in full_dispatch_request\n",
      "    rv = self.dispatch_request()\n",
      "  File \"C:\\Users\\Laverne\\anaconda3\\lib\\site-packages\\flask\\app.py\", line 1796, in dispatch_request\n",
      "    return self.ensure_sync(self.view_functions[rule.endpoint])(**view_args)\n",
      "  File \"C:\\Users\\Laverne\\AppData\\Local\\Temp\\ipykernel_16992\\1007073488.py\", line 416, in get_hist\n",
      "    return jsonify({'hist_src': f'static/histogram.jpg?{timestamp}'})\n",
      "NameError: name 'jsonify' is not defined\n",
      "127.0.0.1 - - [20/Jul/2023 22:46:18] \"GET /get_hist HTTP/1.1\" 500 -\n",
      "[2023-07-20 22:46:18,254] ERROR in app: Exception on /get_hist [GET]\n",
      "Traceback (most recent call last):\n",
      "  File \"C:\\Users\\Laverne\\anaconda3\\lib\\site-packages\\flask\\app.py\", line 2525, in wsgi_app\n",
      "    response = self.full_dispatch_request()\n",
      "  File \"C:\\Users\\Laverne\\anaconda3\\lib\\site-packages\\flask\\app.py\", line 1822, in full_dispatch_request\n",
      "    rv = self.handle_user_exception(e)\n",
      "  File \"C:\\Users\\Laverne\\anaconda3\\lib\\site-packages\\flask\\app.py\", line 1820, in full_dispatch_request\n",
      "    rv = self.dispatch_request()\n",
      "  File \"C:\\Users\\Laverne\\anaconda3\\lib\\site-packages\\flask\\app.py\", line 1796, in dispatch_request\n",
      "    return self.ensure_sync(self.view_functions[rule.endpoint])(**view_args)\n",
      "  File \"C:\\Users\\Laverne\\AppData\\Local\\Temp\\ipykernel_16992\\1007073488.py\", line 416, in get_hist\n",
      "    return jsonify({'hist_src': f'static/histogram.jpg?{timestamp}'})\n",
      "NameError: name 'jsonify' is not defined\n",
      "127.0.0.1 - - [20/Jul/2023 22:46:18] \"GET /get_hist HTTP/1.1\" 500 -\n",
      "[2023-07-20 22:46:20,203] ERROR in app: Exception on /get_graph_data [GET]\n",
      "Traceback (most recent call last):\n",
      "  File \"C:\\Users\\Laverne\\anaconda3\\lib\\site-packages\\flask\\app.py\", line 2525, in wsgi_app\n",
      "    response = self.full_dispatch_request()\n",
      "  File \"C:\\Users\\Laverne\\anaconda3\\lib\\site-packages\\flask\\app.py\", line 1822, in full_dispatch_request\n",
      "    rv = self.handle_user_exception(e)\n",
      "  File \"C:\\Users\\Laverne\\anaconda3\\lib\\site-packages\\flask\\app.py\", line 1820, in full_dispatch_request\n",
      "    rv = self.dispatch_request()\n",
      "  File \"C:\\Users\\Laverne\\anaconda3\\lib\\site-packages\\flask\\app.py\", line 1796, in dispatch_request\n",
      "    return self.ensure_sync(self.view_functions[rule.endpoint])(**view_args)\n",
      "  File \"C:\\Users\\Laverne\\AppData\\Local\\Temp\\ipykernel_16992\\1007073488.py\", line 399, in get_graph_data\n",
      "    return jsonify({'graph_src': f'static/graph.jpg?{timestamp}'})\n",
      "NameError: name 'jsonify' is not defined\n",
      "127.0.0.1 - - [20/Jul/2023 22:46:20] \"GET /get_graph_data HTTP/1.1\" 500 -\n",
      "[2023-07-20 22:46:23,205] ERROR in app: Exception on /get_graph_data [GET]\n",
      "Traceback (most recent call last):\n",
      "  File \"C:\\Users\\Laverne\\anaconda3\\lib\\site-packages\\flask\\app.py\", line 2525, in wsgi_app\n",
      "    response = self.full_dispatch_request()\n",
      "  File \"C:\\Users\\Laverne\\anaconda3\\lib\\site-packages\\flask\\app.py\", line 1822, in full_dispatch_request\n",
      "    rv = self.handle_user_exception(e)\n",
      "  File \"C:\\Users\\Laverne\\anaconda3\\lib\\site-packages\\flask\\app.py\", line 1820, in full_dispatch_request\n",
      "    rv = self.dispatch_request()\n",
      "  File \"C:\\Users\\Laverne\\anaconda3\\lib\\site-packages\\flask\\app.py\", line 1796, in dispatch_request\n",
      "    return self.ensure_sync(self.view_functions[rule.endpoint])(**view_args)\n",
      "  File \"C:\\Users\\Laverne\\AppData\\Local\\Temp\\ipykernel_16992\\1007073488.py\", line 399, in get_graph_data\n",
      "    return jsonify({'graph_src': f'static/graph.jpg?{timestamp}'})\n",
      "NameError: name 'jsonify' is not defined\n",
      "127.0.0.1 - - [20/Jul/2023 22:46:23] \"[2023-07-20 22:46:23,212] ERROR in app: Exception on /get_hist [GET]\n",
      "Traceback (most recent call last):\n",
      "  File \"C:\\Users\\Laverne\\anaconda3\\lib\\site-packages\\flask\\app.py\", line 2525, in wsgi_app\n",
      "    response = self.full_dispatch_request()\n",
      "  File \"C:\\Users\\Laverne\\anaconda3\\lib\\site-packages\\flask\\app.py\", line 1822, in full_dispatch_request\n",
      "    rv = self.handle_user_exception(e)\n",
      "  File \"C:\\Users\\Laverne\\anaconda3\\lib\\site-packages\\flask\\app.py\", line 1820, in full_dispatch_request\n",
      "    rv = self.dispatch_request()\n",
      "  File \"C:\\Users\\Laverne\\anaconda3\\lib\\site-packages\\flask\\app.py\", line 1796, in dispatch_request\n",
      "    return self.ensure_sync(self.view_functions[rule.endpoint])(**view_args)\n",
      "  File \"C:\\Users\\Laverne\\AppData\\Local\\Temp\\ipykernel_16992\\1007073488.py\", line 416, in get_hist\n",
      "    return jsonify({'hist_src': f'static/histogram.jpg?{timestamp}'})\n",
      "NameError: name 'jsonify' is not defined\n",
      "GET /get_graph_data HTTP/1.1\" 500 -\n",
      "127.0.0.1 - - [20/Jul/2023 22:46:23] \"GET /get_hist HTTP/1.1\" 500 -\n",
      "[2023-07-20 22:46:23,259] ERROR in app: Exception on /get_hist [GET]\n",
      "Traceback (most recent call last):\n",
      "  File \"C:\\Users\\Laverne\\anaconda3\\lib\\site-packages\\flask\\app.py\", line 2525, in wsgi_app\n",
      "    response = self.full_dispatch_request()\n",
      "  File \"C:\\Users\\Laverne\\anaconda3\\lib\\site-packages\\flask\\app.py\", line 1822, in full_dispatch_request\n",
      "    rv = self.handle_user_exception(e)\n",
      "  File \"C:\\Users\\Laverne\\anaconda3\\lib\\site-packages\\flask\\app.py\", line 1820, in full_dispatch_request\n",
      "    rv = self.dispatch_request()\n",
      "  File \"C:\\Users\\Laverne\\anaconda3\\lib\\site-packages\\flask\\app.py\", line 1796, in dispatch_request\n",
      "    return self.ensure_sync(self.view_functions[rule.endpoint])(**view_args)\n",
      "  File \"C:\\Users\\Laverne\\AppData\\Local\\Temp\\ipykernel_16992\\1007073488.py\", line 416, in get_hist\n",
      "    return jsonify({'hist_src': f'static/histogram.jpg?{timestamp}'})\n",
      "NameError: name 'jsonify' is not defined\n"
     ]
    },
    {
     "name": "stderr",
     "output_type": "stream",
     "text": [
      "127.0.0.1 - - [20/Jul/2023 22:46:23] \"GET /get_hist HTTP/1.1\" 500 -\n",
      "[2023-07-20 22:46:26,214] ERROR in app: Exception on /get_graph_data [GET]\n",
      "Traceback (most recent call last):\n",
      "  File \"C:\\Users\\Laverne\\anaconda3\\lib\\site-packages\\flask\\app.py\", line 2525, in wsgi_app\n",
      "    response = self.full_dispatch_request()\n",
      "  File \"C:\\Users\\Laverne\\anaconda3\\lib\\site-packages\\flask\\app.py\", line 1822, in full_dispatch_request\n",
      "    rv = self.handle_user_exception(e)\n",
      "  File \"C:\\Users\\Laverne\\anaconda3\\lib\\site-packages\\flask\\app.py\", line 1820, in full_dispatch_request\n",
      "    rv = self.dispatch_request()\n",
      "  File \"C:\\Users\\Laverne\\anaconda3\\lib\\site-packages\\flask\\app.py\", line 1796, in dispatch_request\n",
      "    return self.ensure_sync(self.view_functions[rule.endpoint])(**view_args)\n",
      "  File \"C:\\Users\\Laverne\\AppData\\Local\\Temp\\ipykernel_16992\\1007073488.py\", line 399, in get_graph_data\n",
      "    return jsonify({'graph_src': f'static/graph.jpg?{timestamp}'})\n",
      "NameError: name 'jsonify' is not defined\n",
      "127.0.0.1 - - [20/Jul/2023 22:46:26] \"GET /get_graph_data HTTP/1.1\" 500 -\n",
      "[2023-07-20 22:46:28,200] ERROR in app: Exception on /get_hist [GET]\n",
      "Traceback (most recent call last):\n",
      "  File \"C:\\Users\\Laverne\\anaconda3\\lib\\site-packages\\flask\\app.py\", line 2525, in wsgi_app\n",
      "    response = self.full_dispatch_request()\n",
      "  File \"C:\\Users\\Laverne\\anaconda3\\lib\\site-packages\\flask\\app.py\", line 1822, in full_dispatch_request\n",
      "    rv = self.handle_user_exception(e)\n",
      "  File \"C:\\Users\\Laverne\\anaconda3\\lib\\site-packages\\flask\\app.py\", line 1820, in full_dispatch_request\n",
      "    rv = self.dispatch_request()\n",
      "  File \"C:\\Users\\Laverne\\anaconda3\\lib\\site-packages\\flask\\app.py\", line 1796, in dispatch_request\n",
      "    return self.ensure_sync(self.view_functions[rule.endpoint])(**view_args)\n",
      "  File \"C:\\Users\\Laverne\\AppData\\Local\\Temp\\ipykernel_16992\\1007073488.py\", line 416, in get_hist\n",
      "    return jsonify({'hist_src': f'static/histogram.jpg?{timestamp}'})\n",
      "NameError: name 'jsonify' is not defined\n",
      "127.0.0.1 - - [20/Jul/2023 22:46:28] \"GET /get_hist HTTP/1.1\" 500 -\n",
      "[2023-07-20 22:46:28,212] ERROR in app: Exception on /get_hist [GET]\n",
      "Traceback (most recent call last):\n",
      "  File \"C:\\Users\\Laverne\\anaconda3\\lib\\site-packages\\flask\\app.py\", line 2525, in wsgi_app\n",
      "    response = self.full_dispatch_request()\n",
      "  File \"C:\\Users\\Laverne\\anaconda3\\lib\\site-packages\\flask\\app.py\", line 1822, in full_dispatch_request\n",
      "    rv = self.handle_user_exception(e)\n",
      "  File \"C:\\Users\\Laverne\\anaconda3\\lib\\site-packages\\flask\\app.py\", line 1820, in full_dispatch_request\n",
      "    rv = self.dispatch_request()\n",
      "  File \"C:\\Users\\Laverne\\anaconda3\\lib\\site-packages\\flask\\app.py\", line 1796, in dispatch_request\n",
      "    return self.ensure_sync(self.view_functions[rule.endpoint])(**view_args)\n",
      "  File \"C:\\Users\\Laverne\\AppData\\Local\\Temp\\ipykernel_16992\\1007073488.py\", line 416, in get_hist\n",
      "    return jsonify({'hist_src': f'static/histogram.jpg?{timestamp}'})\n",
      "NameError: name 'jsonify' is not defined\n",
      "127.0.0.1 - - [20/Jul/2023 22:46:28] \"GET /get_hist HTTP/1.1\" 500 -\n",
      "[2023-07-20 22:46:29,211] ERROR in app: Exception on /get_graph_data [GET]\n",
      "Traceback (most recent call last):\n",
      "  File \"C:\\Users\\Laverne\\anaconda3\\lib\\site-packages\\flask\\app.py\", line 2525, in wsgi_app\n",
      "    response = self.full_dispatch_request()\n",
      "  File \"C:\\Users\\Laverne\\anaconda3\\lib\\site-packages\\flask\\app.py\", line 1822, in full_dispatch_request\n",
      "    rv = self.handle_user_exception(e)\n",
      "  File \"C:\\Users\\Laverne\\anaconda3\\lib\\site-packages\\flask\\app.py\", line 1820, in full_dispatch_request\n",
      "    rv = self.dispatch_request()\n",
      "  File \"C:\\Users\\Laverne\\anaconda3\\lib\\site-packages\\flask\\app.py\", line 1796, in dispatch_request\n",
      "    return self.ensure_sync(self.view_functions[rule.endpoint])(**view_args)\n",
      "  File \"C:\\Users\\Laverne\\AppData\\Local\\Temp\\ipykernel_16992\\1007073488.py\", line 399, in get_graph_data\n",
      "    return jsonify({'graph_src': f'static/graph.jpg?{timestamp}'})\n",
      "NameError: name 'jsonify' is not defined\n",
      "127.0.0.1 - - [20/Jul/2023 22:46:29] \"GET /get_graph_data HTTP/1.1\" 500 -\n",
      "[2023-07-20 22:46:32,203] ERROR in app: Exception on /get_graph_data [GET]\n",
      "Traceback (most recent call last):\n",
      "  File \"C:\\Users\\Laverne\\anaconda3\\lib\\site-packages\\flask\\app.py\", line 2525, in wsgi_app\n",
      "    response = self.full_dispatch_request()\n",
      "  File \"C:\\Users\\Laverne\\anaconda3\\lib\\site-packages\\flask\\app.py\", line 1822, in full_dispatch_request\n",
      "    rv = self.handle_user_exception(e)\n",
      "  File \"C:\\Users\\Laverne\\anaconda3\\lib\\site-packages\\flask\\app.py\", line 1820, in full_dispatch_request\n",
      "    rv = self.dispatch_request()\n",
      "  File \"C:\\Users\\Laverne\\anaconda3\\lib\\site-packages\\flask\\app.py\", line 1796, in dispatch_request\n",
      "    return self.ensure_sync(self.view_functions[rule.endpoint])(**view_args)\n",
      "  File \"C:\\Users\\Laverne\\AppData\\Local\\Temp\\ipykernel_16992\\1007073488.py\", line 399, in get_graph_data\n",
      "    return jsonify({'graph_src': f'static/graph.jpg?{timestamp}'})\n",
      "NameError: name 'jsonify' is not defined\n",
      "127.0.0.1 - - [20/Jul/2023 22:46:32] \"GET /get_graph_data HTTP/1.1\" 500 -\n",
      "[2023-07-20 22:46:33,209] ERROR in app: Exception on /get_hist [GET]\n",
      "Traceback (most recent call last):\n",
      "  File \"C:\\Users\\Laverne\\anaconda3\\lib\\site-packages\\flask\\app.py\", line 2525, in wsgi_app\n",
      "    response = self.full_dispatch_request()\n",
      "  File \"C:\\Users\\Laverne\\anaconda3\\lib\\site-packages\\flask\\app.py\", line 1822, in full_dispatch_request\n",
      "    rv = self.handle_user_exception(e)\n",
      "  File \"C:\\Users\\Laverne\\anaconda3\\lib\\site-packages\\flask\\app.py\", line 1820, in full_dispatch_request\n",
      "    rv = self.dispatch_request()\n",
      "  File \"C:\\Users\\Laverne\\anaconda3\\lib\\site-packages\\flask\\app.py\", line 1796, in dispatch_request\n",
      "    return self.ensure_sync(self.view_functions[rule.endpoint])(**view_args)\n",
      "  File \"C:\\Users\\Laverne\\AppData\\Local\\Temp\\ipykernel_16992\\1007073488.py\", line 416, in get_hist\n",
      "    return jsonify({'hist_src': f'static/histogram.jpg?{timestamp}'})\n",
      "NameError: name 'jsonify' is not defined\n",
      "127.0.0.1 - - [20/Jul/2023 22:46:33] \"GET /get_hist HTTP/1.1\" 500 -\n",
      "[2023-07-20 22:46:33,230] ERROR in app: Exception on /get_hist [GET]\n",
      "Traceback (most recent call last):\n",
      "  File \"C:\\Users\\Laverne\\anaconda3\\lib\\site-packages\\flask\\app.py\", line 2525, in wsgi_app\n",
      "    response = self.full_dispatch_request()\n",
      "  File \"C:\\Users\\Laverne\\anaconda3\\lib\\site-packages\\flask\\app.py\", line 1822, in full_dispatch_request\n",
      "    rv = self.handle_user_exception(e)\n",
      "  File \"C:\\Users\\Laverne\\anaconda3\\lib\\site-packages\\flask\\app.py\", line 1820, in full_dispatch_request\n",
      "    rv = self.dispatch_request()\n",
      "  File \"C:\\Users\\Laverne\\anaconda3\\lib\\site-packages\\flask\\app.py\", line 1796, in dispatch_request\n",
      "    return self.ensure_sync(self.view_functions[rule.endpoint])(**view_args)\n",
      "  File \"C:\\Users\\Laverne\\AppData\\Local\\Temp\\ipykernel_16992\\1007073488.py\", line 416, in get_hist\n",
      "    return jsonify({'hist_src': f'static/histogram.jpg?{timestamp}'})\n",
      "NameError: name 'jsonify' is not defined\n",
      "127.0.0.1 - - [20/Jul/2023 22:46:33] \"GET /get_hist HTTP/1.1\" 500 -\n",
      "[2023-07-20 22:46:35,205] ERROR in app: Exception on /get_graph_data [GET]\n",
      "Traceback (most recent call last):\n",
      "  File \"C:\\Users\\Laverne\\anaconda3\\lib\\site-packages\\flask\\app.py\", line 2525, in wsgi_app\n",
      "    response = self.full_dispatch_request()\n",
      "  File \"C:\\Users\\Laverne\\anaconda3\\lib\\site-packages\\flask\\app.py\", line 1822, in full_dispatch_request\n",
      "    rv = self.handle_user_exception(e)\n",
      "  File \"C:\\Users\\Laverne\\anaconda3\\lib\\site-packages\\flask\\app.py\", line 1820, in full_dispatch_request\n",
      "    rv = self.dispatch_request()\n",
      "  File \"C:\\Users\\Laverne\\anaconda3\\lib\\site-packages\\flask\\app.py\", line 1796, in dispatch_request\n",
      "    return self.ensure_sync(self.view_functions[rule.endpoint])(**view_args)\n",
      "  File \"C:\\Users\\Laverne\\AppData\\Local\\Temp\\ipykernel_16992\\1007073488.py\", line 399, in get_graph_data\n",
      "    return jsonify({'graph_src': f'static/graph.jpg?{timestamp}'})\n",
      "NameError: name 'jsonify' is not defined\n",
      "127.0.0.1 - - [20/Jul/2023 22:46:35] \"GET /get_graph_data HTTP/1.1\" 500 -\n",
      "[2023-07-20 22:46:38,213] ERROR in app: Exception on /get_hist [GET]\n",
      "Traceback (most recent call last):\n",
      "  File \"C:\\Users\\Laverne\\anaconda3\\lib\\site-packages\\flask\\app.py\", line 2525, in wsgi_app\n",
      "    response = self.full_dispatch_request()\n",
      "  File \"C:\\Users\\Laverne\\anaconda3\\lib\\site-packages\\flask\\app.py\", line 1822, in full_dispatch_request\n",
      "    rv = self.handle_user_exception(e)\n",
      "  File \"C:\\Users\\Laverne\\anaconda3\\lib\\site-packages\\flask\\app.py\", line 1820, in full_dispatch_request\n",
      "    rv = self.dispatch_request()\n",
      "  File \"C:\\Users\\Laverne\\anaconda3\\lib\\site-packages\\flask\\app.py\", line 1796, in dispatch_request\n",
      "    return self.ensure_sync(self.view_functions[rule.endpoint])(**view_args)\n",
      "  File \"C:\\Users\\Laverne\\AppData\\Local\\Temp\\ipykernel_16992\\1007073488.py\", line 416, in get_hist\n",
      "    return jsonify({'hist_src': f'static/histogram.jpg?{timestamp}'})\n",
      "NameError: name 'jsonify' is not defined\n"
     ]
    },
    {
     "name": "stderr",
     "output_type": "stream",
     "text": [
      "127.0.0.1 - - [20/Jul/2023 22:46:38] \"[2023-07-20 22:46:38,224] ERROR in app: Exception on /get_graph_data [GET]\n",
      "Traceback (most recent call last):\n",
      "  File \"C:\\Users\\Laverne\\anaconda3\\lib\\site-packages\\flask\\app.py\", line 2525, in wsgi_app\n",
      "    response = self.full_dispatch_request()\n",
      "  File \"C:\\Users\\Laverne\\anaconda3\\lib\\site-packages\\flask\\app.py\", line 1822, in full_dispatch_request\n",
      "    rv = self.handle_user_exception(e)\n",
      "  File \"C:\\Users\\Laverne\\anaconda3\\lib\\site-packages\\flask\\app.py\", line 1820, in full_dispatch_request\n",
      "    rv = self.dispatch_request()\n",
      "  File \"C:\\Users\\Laverne\\anaconda3\\lib\\site-packages\\flask\\app.py\", line 1796, in dispatch_request\n",
      "    return self.ensure_sync(self.view_functions[rule.endpoint])(**view_args)\n",
      "  File \"C:\\Users\\Laverne\\AppData\\Local\\Temp\\ipykernel_16992\\1007073488.py\", line 399, in get_graph_data\n",
      "    return jsonify({'graph_src': f'static/graph.jpg?{timestamp}'})\n",
      "NameError: name 'jsonify' is not defined\n",
      "GET /get_hist HTTP/1.1\" 500 -\n",
      "127.0.0.1 - - [20/Jul/2023 22:46:38] \"GET /get_graph_data HTTP/1.1\" 500 -\n",
      "[2023-07-20 22:46:38,294] ERROR in app: Exception on /get_hist [GET]\n",
      "Traceback (most recent call last):\n",
      "  File \"C:\\Users\\Laverne\\anaconda3\\lib\\site-packages\\flask\\app.py\", line 2525, in wsgi_app\n",
      "    response = self.full_dispatch_request()\n",
      "  File \"C:\\Users\\Laverne\\anaconda3\\lib\\site-packages\\flask\\app.py\", line 1822, in full_dispatch_request\n",
      "    rv = self.handle_user_exception(e)\n",
      "  File \"C:\\Users\\Laverne\\anaconda3\\lib\\site-packages\\flask\\app.py\", line 1820, in full_dispatch_request\n",
      "    rv = self.dispatch_request()\n",
      "  File \"C:\\Users\\Laverne\\anaconda3\\lib\\site-packages\\flask\\app.py\", line 1796, in dispatch_request\n",
      "    return self.ensure_sync(self.view_functions[rule.endpoint])(**view_args)\n",
      "  File \"C:\\Users\\Laverne\\AppData\\Local\\Temp\\ipykernel_16992\\1007073488.py\", line 416, in get_hist\n",
      "    return jsonify({'hist_src': f'static/histogram.jpg?{timestamp}'})\n",
      "NameError: name 'jsonify' is not defined\n",
      "127.0.0.1 - - [20/Jul/2023 22:46:38] \"GET /get_hist HTTP/1.1\" 500 -\n",
      "[2023-07-20 22:46:41,211] ERROR in app: Exception on /get_graph_data [GET]\n",
      "Traceback (most recent call last):\n",
      "  File \"C:\\Users\\Laverne\\anaconda3\\lib\\site-packages\\flask\\app.py\", line 2525, in wsgi_app\n",
      "    response = self.full_dispatch_request()\n",
      "  File \"C:\\Users\\Laverne\\anaconda3\\lib\\site-packages\\flask\\app.py\", line 1822, in full_dispatch_request\n",
      "    rv = self.handle_user_exception(e)\n",
      "  File \"C:\\Users\\Laverne\\anaconda3\\lib\\site-packages\\flask\\app.py\", line 1820, in full_dispatch_request\n",
      "    rv = self.dispatch_request()\n",
      "  File \"C:\\Users\\Laverne\\anaconda3\\lib\\site-packages\\flask\\app.py\", line 1796, in dispatch_request\n",
      "    return self.ensure_sync(self.view_functions[rule.endpoint])(**view_args)\n",
      "  File \"C:\\Users\\Laverne\\AppData\\Local\\Temp\\ipykernel_16992\\1007073488.py\", line 399, in get_graph_data\n",
      "    return jsonify({'graph_src': f'static/graph.jpg?{timestamp}'})\n",
      "NameError: name 'jsonify' is not defined\n",
      "127.0.0.1 - - [20/Jul/2023 22:46:41] \"GET /get_graph_data HTTP/1.1\" 500 -\n",
      "[2023-07-20 22:46:43,219] ERROR in app: Exception on /get_hist [GET]\n",
      "Traceback (most recent call last):\n",
      "  File \"C:\\Users\\Laverne\\anaconda3\\lib\\site-packages\\flask\\app.py\", line 2525, in wsgi_app\n",
      "    response = self.full_dispatch_request()\n",
      "  File \"C:\\Users\\Laverne\\anaconda3\\lib\\site-packages\\flask\\app.py\", line 1822, in full_dispatch_request\n",
      "    rv = self.handle_user_exception(e)\n",
      "  File \"C:\\Users\\Laverne\\anaconda3\\lib\\site-packages\\flask\\app.py\", line 1820, in full_dispatch_request\n",
      "    rv = self.dispatch_request()\n",
      "  File \"C:\\Users\\Laverne\\anaconda3\\lib\\site-packages\\flask\\app.py\", line 1796, in dispatch_request\n",
      "    return self.ensure_sync(self.view_functions[rule.endpoint])(**view_args)\n",
      "  File \"C:\\Users\\Laverne\\AppData\\Local\\Temp\\ipykernel_16992\\1007073488.py\", line 416, in get_hist\n",
      "    return jsonify({'hist_src': f'static/histogram.jpg?{timestamp}'})\n",
      "NameError: name 'jsonify' is not defined\n",
      "127.0.0.1 - - [20/Jul/2023 22:46:43] \"GET /get_hist HTTP/1.1\" 500 -\n",
      "[2023-07-20 22:46:43,237] ERROR in app: Exception on /get_hist [GET]\n",
      "Traceback (most recent call last):\n",
      "  File \"C:\\Users\\Laverne\\anaconda3\\lib\\site-packages\\flask\\app.py\", line 2525, in wsgi_app\n",
      "    response = self.full_dispatch_request()\n",
      "  File \"C:\\Users\\Laverne\\anaconda3\\lib\\site-packages\\flask\\app.py\", line 1822, in full_dispatch_request\n",
      "    rv = self.handle_user_exception(e)\n",
      "  File \"C:\\Users\\Laverne\\anaconda3\\lib\\site-packages\\flask\\app.py\", line 1820, in full_dispatch_request\n",
      "    rv = self.dispatch_request()\n",
      "  File \"C:\\Users\\Laverne\\anaconda3\\lib\\site-packages\\flask\\app.py\", line 1796, in dispatch_request\n",
      "    return self.ensure_sync(self.view_functions[rule.endpoint])(**view_args)\n",
      "  File \"C:\\Users\\Laverne\\AppData\\Local\\Temp\\ipykernel_16992\\1007073488.py\", line 416, in get_hist\n",
      "    return jsonify({'hist_src': f'static/histogram.jpg?{timestamp}'})\n",
      "NameError: name 'jsonify' is not defined\n",
      "127.0.0.1 - - [20/Jul/2023 22:46:43] \"GET /get_hist HTTP/1.1\" 500 -\n",
      "[2023-07-20 22:46:44,214] ERROR in app: Exception on /get_graph_data [GET]\n",
      "Traceback (most recent call last):\n",
      "  File \"C:\\Users\\Laverne\\anaconda3\\lib\\site-packages\\flask\\app.py\", line 2525, in wsgi_app\n",
      "    response = self.full_dispatch_request()\n",
      "  File \"C:\\Users\\Laverne\\anaconda3\\lib\\site-packages\\flask\\app.py\", line 1822, in full_dispatch_request\n",
      "    rv = self.handle_user_exception(e)\n",
      "  File \"C:\\Users\\Laverne\\anaconda3\\lib\\site-packages\\flask\\app.py\", line 1820, in full_dispatch_request\n",
      "    rv = self.dispatch_request()\n",
      "  File \"C:\\Users\\Laverne\\anaconda3\\lib\\site-packages\\flask\\app.py\", line 1796, in dispatch_request\n",
      "    return self.ensure_sync(self.view_functions[rule.endpoint])(**view_args)\n",
      "  File \"C:\\Users\\Laverne\\AppData\\Local\\Temp\\ipykernel_16992\\1007073488.py\", line 399, in get_graph_data\n",
      "    return jsonify({'graph_src': f'static/graph.jpg?{timestamp}'})\n",
      "NameError: name 'jsonify' is not defined\n",
      "127.0.0.1 - - [20/Jul/2023 22:46:44] \"GET /get_graph_data HTTP/1.1\" 500 -\n",
      "[2023-07-20 22:46:46,228] ERROR in app: Exception on /get_graph_data [GET]\n",
      "Traceback (most recent call last):\n",
      "  File \"C:\\Users\\Laverne\\anaconda3\\lib\\site-packages\\flask\\app.py\", line 2525, in wsgi_app\n",
      "    response = self.full_dispatch_request()\n",
      "  File \"C:\\Users\\Laverne\\anaconda3\\lib\\site-packages\\flask\\app.py\", line 1822, in full_dispatch_request\n",
      "    rv = self.handle_user_exception(e)\n",
      "  File \"C:\\Users\\Laverne\\anaconda3\\lib\\site-packages\\flask\\app.py\", line 1820, in full_dispatch_request\n",
      "    rv = self.dispatch_request()\n",
      "  File \"C:\\Users\\Laverne\\anaconda3\\lib\\site-packages\\flask\\app.py\", line 1796, in dispatch_request\n",
      "    return self.ensure_sync(self.view_functions[rule.endpoint])(**view_args)\n",
      "  File \"C:\\Users\\Laverne\\AppData\\Local\\Temp\\ipykernel_16992\\1007073488.py\", line 399, in get_graph_data\n",
      "    return jsonify({'graph_src': f'static/graph.jpg?{timestamp}'})\n",
      "NameError: name 'jsonify' is not defined\n",
      "127.0.0.1 - - [20/Jul/2023 22:46:46] \"GET /get_graph_data HTTP/1.1\" 500 -\n",
      "[2023-07-20 22:46:47,249] ERROR in app: Exception on /get_hist [GET]\n",
      "Traceback (most recent call last):\n",
      "  File \"C:\\Users\\Laverne\\anaconda3\\lib\\site-packages\\flask\\app.py\", line 2525, in wsgi_app\n",
      "    response = self.full_dispatch_request()\n",
      "  File \"C:\\Users\\Laverne\\anaconda3\\lib\\site-packages\\flask\\app.py\", line 1822, in full_dispatch_request\n",
      "    rv = self.handle_user_exception(e)\n",
      "  File \"C:\\Users\\Laverne\\anaconda3\\lib\\site-packages\\flask\\app.py\", line 1820, in full_dispatch_request\n",
      "    rv = self.dispatch_request()\n",
      "  File \"C:\\Users\\Laverne\\anaconda3\\lib\\site-packages\\flask\\app.py\", line 1796, in dispatch_request\n",
      "    return self.ensure_sync(self.view_functions[rule.endpoint])(**view_args)\n",
      "  File \"C:\\Users\\Laverne\\AppData\\Local\\Temp\\ipykernel_16992\\1007073488.py\", line 416, in get_hist\n",
      "    return jsonify({'hist_src': f'static/histogram.jpg?{timestamp}'})\n",
      "NameError: name 'jsonify' is not defined\n",
      "127.0.0.1 - - [20/Jul/2023 22:46:47] \"GET /get_hist HTTP/1.1\" 500 -\n",
      "[2023-07-20 22:46:47,272] ERROR in app: Exception on /get_hist [GET]\n",
      "Traceback (most recent call last):\n",
      "  File \"C:\\Users\\Laverne\\anaconda3\\lib\\site-packages\\flask\\app.py\", line 2525, in wsgi_app\n",
      "    response = self.full_dispatch_request()\n",
      "  File \"C:\\Users\\Laverne\\anaconda3\\lib\\site-packages\\flask\\app.py\", line 1822, in full_dispatch_request\n",
      "    rv = self.handle_user_exception(e)\n",
      "  File \"C:\\Users\\Laverne\\anaconda3\\lib\\site-packages\\flask\\app.py\", line 1820, in full_dispatch_request\n",
      "    rv = self.dispatch_request()\n",
      "  File \"C:\\Users\\Laverne\\anaconda3\\lib\\site-packages\\flask\\app.py\", line 1796, in dispatch_request\n",
      "    return self.ensure_sync(self.view_functions[rule.endpoint])(**view_args)\n",
      "  File \"C:\\Users\\Laverne\\AppData\\Local\\Temp\\ipykernel_16992\\1007073488.py\", line 416, in get_hist\n",
      "    return jsonify({'hist_src': f'static/histogram.jpg?{timestamp}'})\n",
      "NameError: name 'jsonify' is not defined\n"
     ]
    },
    {
     "name": "stderr",
     "output_type": "stream",
     "text": [
      "127.0.0.1 - - [20/Jul/2023 22:46:47] \"GET /get_hist HTTP/1.1\" 500 -\n",
      "[2023-07-20 22:46:48,255] ERROR in app: Exception on /get_graph_data [GET]\n",
      "Traceback (most recent call last):\n",
      "  File \"C:\\Users\\Laverne\\anaconda3\\lib\\site-packages\\flask\\app.py\", line 2525, in wsgi_app\n",
      "    response = self.full_dispatch_request()\n",
      "  File \"C:\\Users\\Laverne\\anaconda3\\lib\\site-packages\\flask\\app.py\", line 1822, in full_dispatch_request\n",
      "    rv = self.handle_user_exception(e)\n",
      "  File \"C:\\Users\\Laverne\\anaconda3\\lib\\site-packages\\flask\\app.py\", line 1820, in full_dispatch_request\n",
      "    rv = self.dispatch_request()\n",
      "  File \"C:\\Users\\Laverne\\anaconda3\\lib\\site-packages\\flask\\app.py\", line 1796, in dispatch_request\n",
      "    return self.ensure_sync(self.view_functions[rule.endpoint])(**view_args)\n",
      "  File \"C:\\Users\\Laverne\\AppData\\Local\\Temp\\ipykernel_16992\\1007073488.py\", line 399, in get_graph_data\n",
      "    return jsonify({'graph_src': f'static/graph.jpg?{timestamp}'})\n",
      "NameError: name 'jsonify' is not defined\n",
      "127.0.0.1 - - [20/Jul/2023 22:46:48] \"GET /get_graph_data HTTP/1.1\" 500 -\n",
      "[2023-07-20 22:46:50,284] ERROR in app: Exception on /get_graph_data [GET]\n",
      "Traceback (most recent call last):\n",
      "  File \"C:\\Users\\Laverne\\anaconda3\\lib\\site-packages\\flask\\app.py\", line 2525, in wsgi_app\n",
      "    response = self.full_dispatch_request()\n",
      "  File \"C:\\Users\\Laverne\\anaconda3\\lib\\site-packages\\flask\\app.py\", line 1822, in full_dispatch_request\n",
      "    rv = self.handle_user_exception(e)\n",
      "  File \"C:\\Users\\Laverne\\anaconda3\\lib\\site-packages\\flask\\app.py\", line 1820, in full_dispatch_request\n",
      "    rv = self.dispatch_request()\n",
      "  File \"C:\\Users\\Laverne\\anaconda3\\lib\\site-packages\\flask\\app.py\", line 1796, in dispatch_request\n",
      "    return self.ensure_sync(self.view_functions[rule.endpoint])(**view_args)\n",
      "  File \"C:\\Users\\Laverne\\AppData\\Local\\Temp\\ipykernel_16992\\1007073488.py\", line 399, in get_graph_data\n",
      "    return jsonify({'graph_src': f'static/graph.jpg?{timestamp}'})\n",
      "NameError: name 'jsonify' is not defined\n",
      "127.0.0.1 - - [20/Jul/2023 22:46:50] \"GET /get_graph_data HTTP/1.1\" 500 -\n",
      "[2023-07-20 22:46:51,274] ERROR in app: Exception on /get_hist [GET]\n",
      "Traceback (most recent call last):\n",
      "  File \"C:\\Users\\Laverne\\anaconda3\\lib\\site-packages\\flask\\app.py\", line 2525, in wsgi_app\n",
      "    response = self.full_dispatch_request()\n",
      "  File \"C:\\Users\\Laverne\\anaconda3\\lib\\site-packages\\flask\\app.py\", line 1822, in full_dispatch_request\n",
      "    rv = self.handle_user_exception(e)\n",
      "  File \"C:\\Users\\Laverne\\anaconda3\\lib\\site-packages\\flask\\app.py\", line 1820, in full_dispatch_request\n",
      "    rv = self.dispatch_request()\n",
      "  File \"C:\\Users\\Laverne\\anaconda3\\lib\\site-packages\\flask\\app.py\", line 1796, in dispatch_request\n",
      "    return self.ensure_sync(self.view_functions[rule.endpoint])(**view_args)\n",
      "  File \"C:\\Users\\Laverne\\AppData\\Local\\Temp\\ipykernel_16992\\1007073488.py\", line 416, in get_hist\n",
      "    return jsonify({'hist_src': f'static/histogram.jpg?{timestamp}'})\n",
      "NameError: name 'jsonify' is not defined\n",
      "127.0.0.1 - - [20/Jul/2023 22:46:51] \"GET /get_hist HTTP/1.1\" 500 -\n",
      "[2023-07-20 22:46:51,302] ERROR in app: Exception on /get_hist [GET]\n",
      "Traceback (most recent call last):\n",
      "  File \"C:\\Users\\Laverne\\anaconda3\\lib\\site-packages\\flask\\app.py\", line 2525, in wsgi_app\n",
      "    response = self.full_dispatch_request()\n",
      "  File \"C:\\Users\\Laverne\\anaconda3\\lib\\site-packages\\flask\\app.py\", line 1822, in full_dispatch_request\n",
      "    rv = self.handle_user_exception(e)\n",
      "  File \"C:\\Users\\Laverne\\anaconda3\\lib\\site-packages\\flask\\app.py\", line 1820, in full_dispatch_request\n",
      "    rv = self.dispatch_request()\n",
      "  File \"C:\\Users\\Laverne\\anaconda3\\lib\\site-packages\\flask\\app.py\", line 1796, in dispatch_request\n",
      "    return self.ensure_sync(self.view_functions[rule.endpoint])(**view_args)\n",
      "  File \"C:\\Users\\Laverne\\AppData\\Local\\Temp\\ipykernel_16992\\1007073488.py\", line 416, in get_hist\n",
      "    return jsonify({'hist_src': f'static/histogram.jpg?{timestamp}'})\n",
      "NameError: name 'jsonify' is not defined\n",
      "127.0.0.1 - - [20/Jul/2023 22:46:51] \"GET /get_hist HTTP/1.1\" 500 -\n",
      "[2023-07-20 22:46:52,322] ERROR in app: Exception on /get_graph_data [GET]\n",
      "Traceback (most recent call last):\n",
      "  File \"C:\\Users\\Laverne\\anaconda3\\lib\\site-packages\\flask\\app.py\", line 2525, in wsgi_app\n",
      "    response = self.full_dispatch_request()\n",
      "  File \"C:\\Users\\Laverne\\anaconda3\\lib\\site-packages\\flask\\app.py\", line 1822, in full_dispatch_request\n",
      "    rv = self.handle_user_exception(e)\n",
      "  File \"C:\\Users\\Laverne\\anaconda3\\lib\\site-packages\\flask\\app.py\", line 1820, in full_dispatch_request\n",
      "    rv = self.dispatch_request()\n",
      "  File \"C:\\Users\\Laverne\\anaconda3\\lib\\site-packages\\flask\\app.py\", line 1796, in dispatch_request\n",
      "    return self.ensure_sync(self.view_functions[rule.endpoint])(**view_args)\n",
      "  File \"C:\\Users\\Laverne\\AppData\\Local\\Temp\\ipykernel_16992\\1007073488.py\", line 399, in get_graph_data\n",
      "    return jsonify({'graph_src': f'static/graph.jpg?{timestamp}'})\n",
      "NameError: name 'jsonify' is not defined\n",
      "127.0.0.1 - - [20/Jul/2023 22:46:52] \"GET /get_graph_data HTTP/1.1\" 500 -\n",
      "[2023-07-20 22:46:54,354] ERROR in app: Exception on /get_graph_data [GET]\n",
      "Traceback (most recent call last):\n",
      "  File \"C:\\Users\\Laverne\\anaconda3\\lib\\site-packages\\flask\\app.py\", line 2525, in wsgi_app\n",
      "    response = self.full_dispatch_request()\n",
      "  File \"C:\\Users\\Laverne\\anaconda3\\lib\\site-packages\\flask\\app.py\", line 1822, in full_dispatch_request\n",
      "    rv = self.handle_user_exception(e)\n",
      "  File \"C:\\Users\\Laverne\\anaconda3\\lib\\site-packages\\flask\\app.py\", line 1820, in full_dispatch_request\n",
      "    rv = self.dispatch_request()\n",
      "  File \"C:\\Users\\Laverne\\anaconda3\\lib\\site-packages\\flask\\app.py\", line 1796, in dispatch_request\n",
      "    return self.ensure_sync(self.view_functions[rule.endpoint])(**view_args)\n",
      "  File \"C:\\Users\\Laverne\\AppData\\Local\\Temp\\ipykernel_16992\\1007073488.py\", line 399, in get_graph_data\n",
      "    return jsonify({'graph_src': f'static/graph.jpg?{timestamp}'})\n",
      "NameError: name 'jsonify' is not defined\n",
      "127.0.0.1 - - [20/Jul/2023 22:46:54] \"GET /get_graph_data HTTP/1.1\" 500 -\n",
      "[2023-07-20 22:46:55,303] ERROR in app: Exception on /get_hist [GET]\n",
      "Traceback (most recent call last):\n",
      "  File \"C:\\Users\\Laverne\\anaconda3\\lib\\site-packages\\flask\\app.py\", line 2525, in wsgi_app\n",
      "    response = self.full_dispatch_request()\n",
      "  File \"C:\\Users\\Laverne\\anaconda3\\lib\\site-packages\\flask\\app.py\", line 1822, in full_dispatch_request\n",
      "    rv = self.handle_user_exception(e)\n",
      "  File \"C:\\Users\\Laverne\\anaconda3\\lib\\site-packages\\flask\\app.py\", line 1820, in full_dispatch_request\n",
      "    rv = self.dispatch_request()\n",
      "  File \"C:\\Users\\Laverne\\anaconda3\\lib\\site-packages\\flask\\app.py\", line 1796, in dispatch_request\n",
      "    return self.ensure_sync(self.view_functions[rule.endpoint])(**view_args)\n",
      "  File \"C:\\Users\\Laverne\\AppData\\Local\\Temp\\ipykernel_16992\\1007073488.py\", line 416, in get_hist\n",
      "    return jsonify({'hist_src': f'static/histogram.jpg?{timestamp}'})\n",
      "NameError: name 'jsonify' is not defined\n",
      "127.0.0.1 - - [20/Jul/2023 22:46:55] \"GET /get_hist HTTP/1.1\" 500 -\n",
      "[2023-07-20 22:46:55,333] ERROR in app: Exception on /get_hist [GET]\n",
      "Traceback (most recent call last):\n",
      "  File \"C:\\Users\\Laverne\\anaconda3\\lib\\site-packages\\flask\\app.py\", line 2525, in wsgi_app\n",
      "    response = self.full_dispatch_request()\n",
      "  File \"C:\\Users\\Laverne\\anaconda3\\lib\\site-packages\\flask\\app.py\", line 1822, in full_dispatch_request\n",
      "    rv = self.handle_user_exception(e)\n",
      "  File \"C:\\Users\\Laverne\\anaconda3\\lib\\site-packages\\flask\\app.py\", line 1820, in full_dispatch_request\n",
      "    rv = self.dispatch_request()\n",
      "  File \"C:\\Users\\Laverne\\anaconda3\\lib\\site-packages\\flask\\app.py\", line 1796, in dispatch_request\n",
      "    return self.ensure_sync(self.view_functions[rule.endpoint])(**view_args)\n",
      "  File \"C:\\Users\\Laverne\\AppData\\Local\\Temp\\ipykernel_16992\\1007073488.py\", line 416, in get_hist\n",
      "    return jsonify({'hist_src': f'static/histogram.jpg?{timestamp}'})\n",
      "NameError: name 'jsonify' is not defined\n",
      "127.0.0.1 - - [20/Jul/2023 22:46:55] \"GET /get_hist HTTP/1.1\" 500 -\n",
      "[2023-07-20 22:46:56,382] ERROR in app: Exception on /get_graph_data [GET]\n",
      "Traceback (most recent call last):\n",
      "  File \"C:\\Users\\Laverne\\anaconda3\\lib\\site-packages\\flask\\app.py\", line 2525, in wsgi_app\n",
      "    response = self.full_dispatch_request()\n",
      "  File \"C:\\Users\\Laverne\\anaconda3\\lib\\site-packages\\flask\\app.py\", line 1822, in full_dispatch_request\n",
      "    rv = self.handle_user_exception(e)\n",
      "  File \"C:\\Users\\Laverne\\anaconda3\\lib\\site-packages\\flask\\app.py\", line 1820, in full_dispatch_request\n",
      "    rv = self.dispatch_request()\n",
      "  File \"C:\\Users\\Laverne\\anaconda3\\lib\\site-packages\\flask\\app.py\", line 1796, in dispatch_request\n",
      "    return self.ensure_sync(self.view_functions[rule.endpoint])(**view_args)\n",
      "  File \"C:\\Users\\Laverne\\AppData\\Local\\Temp\\ipykernel_16992\\1007073488.py\", line 399, in get_graph_data\n",
      "    return jsonify({'graph_src': f'static/graph.jpg?{timestamp}'})\n",
      "NameError: name 'jsonify' is not defined\n"
     ]
    },
    {
     "name": "stderr",
     "output_type": "stream",
     "text": [
      "127.0.0.1 - - [20/Jul/2023 22:46:56] \"GET /get_graph_data HTTP/1.1\" 500 -\n",
      "[2023-07-20 22:46:58,414] ERROR in app: Exception on /get_graph_data [GET]\n",
      "Traceback (most recent call last):\n",
      "  File \"C:\\Users\\Laverne\\anaconda3\\lib\\site-packages\\flask\\app.py\", line 2525, in wsgi_app\n",
      "    response = self.full_dispatch_request()\n",
      "  File \"C:\\Users\\Laverne\\anaconda3\\lib\\site-packages\\flask\\app.py\", line 1822, in full_dispatch_request\n",
      "    rv = self.handle_user_exception(e)\n",
      "  File \"C:\\Users\\Laverne\\anaconda3\\lib\\site-packages\\flask\\app.py\", line 1820, in full_dispatch_request\n",
      "    rv = self.dispatch_request()\n",
      "  File \"C:\\Users\\Laverne\\anaconda3\\lib\\site-packages\\flask\\app.py\", line 1796, in dispatch_request\n",
      "    return self.ensure_sync(self.view_functions[rule.endpoint])(**view_args)\n",
      "  File \"C:\\Users\\Laverne\\AppData\\Local\\Temp\\ipykernel_16992\\1007073488.py\", line 399, in get_graph_data\n",
      "    return jsonify({'graph_src': f'static/graph.jpg?{timestamp}'})\n",
      "NameError: name 'jsonify' is not defined\n",
      "127.0.0.1 - - [20/Jul/2023 22:46:58] \"GET /get_graph_data HTTP/1.1\" 500 -\n",
      "[2023-07-20 22:46:59,332] ERROR in app: Exception on /get_hist [GET]\n",
      "Traceback (most recent call last):\n",
      "  File \"C:\\Users\\Laverne\\anaconda3\\lib\\site-packages\\flask\\app.py\", line 2525, in wsgi_app\n",
      "    response = self.full_dispatch_request()\n",
      "  File \"C:\\Users\\Laverne\\anaconda3\\lib\\site-packages\\flask\\app.py\", line 1822, in full_dispatch_request\n",
      "    rv = self.handle_user_exception(e)\n",
      "  File \"C:\\Users\\Laverne\\anaconda3\\lib\\site-packages\\flask\\app.py\", line 1820, in full_dispatch_request\n",
      "    rv = self.dispatch_request()\n",
      "  File \"C:\\Users\\Laverne\\anaconda3\\lib\\site-packages\\flask\\app.py\", line 1796, in dispatch_request\n",
      "    return self.ensure_sync(self.view_functions[rule.endpoint])(**view_args)\n",
      "  File \"C:\\Users\\Laverne\\AppData\\Local\\Temp\\ipykernel_16992\\1007073488.py\", line 416, in get_hist\n",
      "    return jsonify({'hist_src': f'static/histogram.jpg?{timestamp}'})\n",
      "NameError: name 'jsonify' is not defined\n",
      "127.0.0.1 - - [20/Jul/2023 22:46:59] \"GET /get_hist HTTP/1.1\" 500 -\n",
      "[2023-07-20 22:46:59,369] ERROR in app: Exception on /get_hist [GET]\n",
      "Traceback (most recent call last):\n",
      "  File \"C:\\Users\\Laverne\\anaconda3\\lib\\site-packages\\flask\\app.py\", line 2525, in wsgi_app\n",
      "    response = self.full_dispatch_request()\n",
      "  File \"C:\\Users\\Laverne\\anaconda3\\lib\\site-packages\\flask\\app.py\", line 1822, in full_dispatch_request\n",
      "    rv = self.handle_user_exception(e)\n",
      "  File \"C:\\Users\\Laverne\\anaconda3\\lib\\site-packages\\flask\\app.py\", line 1820, in full_dispatch_request\n",
      "    rv = self.dispatch_request()\n",
      "  File \"C:\\Users\\Laverne\\anaconda3\\lib\\site-packages\\flask\\app.py\", line 1796, in dispatch_request\n",
      "    return self.ensure_sync(self.view_functions[rule.endpoint])(**view_args)\n",
      "  File \"C:\\Users\\Laverne\\AppData\\Local\\Temp\\ipykernel_16992\\1007073488.py\", line 416, in get_hist\n",
      "    return jsonify({'hist_src': f'static/histogram.jpg?{timestamp}'})\n",
      "NameError: name 'jsonify' is not defined\n",
      "127.0.0.1 - - [20/Jul/2023 22:46:59] \"GET /get_hist HTTP/1.1\" 500 -\n",
      "[2023-07-20 22:47:00,443] ERROR in app: Exception on /get_graph_data [GET]\n",
      "Traceback (most recent call last):\n",
      "  File \"C:\\Users\\Laverne\\anaconda3\\lib\\site-packages\\flask\\app.py\", line 2525, in wsgi_app\n",
      "    response = self.full_dispatch_request()\n",
      "  File \"C:\\Users\\Laverne\\anaconda3\\lib\\site-packages\\flask\\app.py\", line 1822, in full_dispatch_request\n",
      "    rv = self.handle_user_exception(e)\n",
      "  File \"C:\\Users\\Laverne\\anaconda3\\lib\\site-packages\\flask\\app.py\", line 1820, in full_dispatch_request\n",
      "    rv = self.dispatch_request()\n",
      "  File \"C:\\Users\\Laverne\\anaconda3\\lib\\site-packages\\flask\\app.py\", line 1796, in dispatch_request\n",
      "    return self.ensure_sync(self.view_functions[rule.endpoint])(**view_args)\n",
      "  File \"C:\\Users\\Laverne\\AppData\\Local\\Temp\\ipykernel_16992\\1007073488.py\", line 399, in get_graph_data\n",
      "    return jsonify({'graph_src': f'static/graph.jpg?{timestamp}'})\n",
      "NameError: name 'jsonify' is not defined\n",
      "127.0.0.1 - - [20/Jul/2023 22:47:00] \"GET /get_graph_data HTTP/1.1\" 500 -\n",
      "[2023-07-20 22:47:02,459] ERROR in app: Exception on /get_graph_data [GET]\n",
      "Traceback (most recent call last):\n",
      "  File \"C:\\Users\\Laverne\\anaconda3\\lib\\site-packages\\flask\\app.py\", line 2525, in wsgi_app\n",
      "    response = self.full_dispatch_request()\n",
      "  File \"C:\\Users\\Laverne\\anaconda3\\lib\\site-packages\\flask\\app.py\", line 1822, in full_dispatch_request\n",
      "    rv = self.handle_user_exception(e)\n",
      "  File \"C:\\Users\\Laverne\\anaconda3\\lib\\site-packages\\flask\\app.py\", line 1820, in full_dispatch_request\n",
      "    rv = self.dispatch_request()\n",
      "  File \"C:\\Users\\Laverne\\anaconda3\\lib\\site-packages\\flask\\app.py\", line 1796, in dispatch_request\n",
      "    return self.ensure_sync(self.view_functions[rule.endpoint])(**view_args)\n",
      "  File \"C:\\Users\\Laverne\\AppData\\Local\\Temp\\ipykernel_16992\\1007073488.py\", line 399, in get_graph_data\n",
      "    return jsonify({'graph_src': f'static/graph.jpg?{timestamp}'})\n",
      "NameError: name 'jsonify' is not defined\n",
      "127.0.0.1 - - [20/Jul/2023 22:47:02] \"GET /get_graph_data HTTP/1.1\" 500 -\n",
      "[2023-07-20 22:47:03,362] ERROR in app: Exception on /get_hist [GET]\n",
      "Traceback (most recent call last):\n",
      "  File \"C:\\Users\\Laverne\\anaconda3\\lib\\site-packages\\flask\\app.py\", line 2525, in wsgi_app\n",
      "    response = self.full_dispatch_request()\n",
      "  File \"C:\\Users\\Laverne\\anaconda3\\lib\\site-packages\\flask\\app.py\", line 1822, in full_dispatch_request\n",
      "    rv = self.handle_user_exception(e)\n",
      "  File \"C:\\Users\\Laverne\\anaconda3\\lib\\site-packages\\flask\\app.py\", line 1820, in full_dispatch_request\n",
      "    rv = self.dispatch_request()\n",
      "  File \"C:\\Users\\Laverne\\anaconda3\\lib\\site-packages\\flask\\app.py\", line 1796, in dispatch_request\n",
      "    return self.ensure_sync(self.view_functions[rule.endpoint])(**view_args)\n",
      "  File \"C:\\Users\\Laverne\\AppData\\Local\\Temp\\ipykernel_16992\\1007073488.py\", line 416, in get_hist\n",
      "    return jsonify({'hist_src': f'static/histogram.jpg?{timestamp}'})\n",
      "NameError: name 'jsonify' is not defined\n",
      "127.0.0.1 - - [20/Jul/2023 22:47:03] \"GET /get_hist HTTP/1.1\" 500 -\n",
      "[2023-07-20 22:47:03,413] ERROR in app: Exception on /get_hist [GET]\n",
      "Traceback (most recent call last):\n",
      "  File \"C:\\Users\\Laverne\\anaconda3\\lib\\site-packages\\flask\\app.py\", line 2525, in wsgi_app\n",
      "    response = self.full_dispatch_request()\n",
      "  File \"C:\\Users\\Laverne\\anaconda3\\lib\\site-packages\\flask\\app.py\", line 1822, in full_dispatch_request\n",
      "    rv = self.handle_user_exception(e)\n",
      "  File \"C:\\Users\\Laverne\\anaconda3\\lib\\site-packages\\flask\\app.py\", line 1820, in full_dispatch_request\n",
      "    rv = self.dispatch_request()\n",
      "  File \"C:\\Users\\Laverne\\anaconda3\\lib\\site-packages\\flask\\app.py\", line 1796, in dispatch_request\n",
      "    return self.ensure_sync(self.view_functions[rule.endpoint])(**view_args)\n",
      "  File \"C:\\Users\\Laverne\\AppData\\Local\\Temp\\ipykernel_16992\\1007073488.py\", line 416, in get_hist\n",
      "    return jsonify({'hist_src': f'static/histogram.jpg?{timestamp}'})\n",
      "NameError: name 'jsonify' is not defined\n",
      "127.0.0.1 - - [20/Jul/2023 22:47:03] \"GET /get_hist HTTP/1.1\" 500 -\n",
      "[2023-07-20 22:47:03,951] ERROR in app: Exception on / [POST]\n",
      "Traceback (most recent call last):\n",
      "  File \"C:\\Users\\Laverne\\anaconda3\\lib\\site-packages\\flask\\app.py\", line 2525, in wsgi_app\n",
      "    response = self.full_dispatch_request()\n",
      "  File \"C:\\Users\\Laverne\\anaconda3\\lib\\site-packages\\flask\\app.py\", line 1822, in full_dispatch_request\n",
      "    rv = self.handle_user_exception(e)\n",
      "  File \"C:\\Users\\Laverne\\anaconda3\\lib\\site-packages\\flask\\app.py\", line 1820, in full_dispatch_request\n",
      "    rv = self.dispatch_request()\n",
      "  File \"C:\\Users\\Laverne\\anaconda3\\lib\\site-packages\\flask\\app.py\", line 1796, in dispatch_request\n",
      "    return self.ensure_sync(self.view_functions[rule.endpoint])(**view_args)\n",
      "  File \"C:\\Users\\Laverne\\AppData\\Local\\Temp\\ipykernel_16992\\1007073488.py\", line 63, in index\n",
      "    feature_map, ansatz_curcuit = create_feature_map(feature_map_type, pca_no, entang)\n",
      "  File \"C:\\Users\\Laverne\\AppData\\Local\\Temp\\ipykernel_16992\\1007073488.py\", line 135, in create_feature_map\n",
      "    feature_map = ZFeatureMap(feature_dimension=fdimension, reps=1, entanglement=entang)\n",
      "TypeError: ZFeatureMap.__init__() got an unexpected keyword argument 'entanglement'\n",
      "127.0.0.1 - - [20/Jul/2023 22:47:03] \"POST / HTTP/1.1\" 500 -\n"
     ]
    }
   ],
   "source": [
    "from flask import Flask, render_template, request\n",
    "import numpy as np\n",
    "import pandas as pd\n",
    "import base64\n",
    "import io \n",
    "import base64\n",
    "import matplotlib.pyplot as plt\n",
    "from sklearn import datasets\n",
    "from sklearn.model_selection import train_test_split\n",
    "from sklearn.preprocessing import MinMaxScaler\n",
    "from sklearn.decomposition import PCA\n",
    "from sklearn import decomposition\n",
    "\n",
    "\n",
    "from qiskit import Aer\n",
    "from qiskit import transpile, execute\n",
    "from qiskit.circuit.library import ZZFeatureMap, ZFeatureMap, PauliFeatureMap\n",
    "from qiskit.circuit.library import RealAmplitudes\n",
    "from qiskit.algorithms.optimizers import SPSA\n",
    "from qiskit_machine_learning.algorithms import VQC\n",
    "from qiskit_machine_learning.kernels import QuantumKernel\n",
    "from qiskit_machine_learning.exceptions import QiskitMachineLearningError\n",
    "from azure.quantum import Workspace\n",
    "from azure.quantum.qiskit import AzureQuantumProvider\n",
    "from qiskit.visualization import circuit_drawer\n",
    "import time\n",
    "\n",
    "\n",
    "\n",
    "app = Flask(__name__,static_folder='static')\n",
    "\n",
    "@app.route('/',methods=['GET', 'POST'])\n",
    "def index():\n",
    "    \n",
    "\n",
    "\n",
    "    if request.method == 'POST':\n",
    "        \n",
    "        model = request.form['model']\n",
    "        dataset = request.form['dataset']\n",
    "        feature_map_type = request.form['featuremap']\n",
    "        optimizer_type = request.form['optimizer']\n",
    "        split = request.form['split']\n",
    "        pca_no = request.form['pca']\n",
    "        pca_no = int(pca_no)\n",
    "        entang = request.form['entang']\n",
    "        \n",
    "        \n",
    "        \n",
    "        \n",
    "        X,y= load_dataset(dataset)\n",
    "        \n",
    "        X = pca(pca_no, X)\n",
    "        \n",
    "        test_size = split_ratio(split)\n",
    "        \n",
    "        X_train, X_test, y_train, y_test = train_test_split(X, y, test_size=test_size, random_state=42)\n",
    "        \n",
    "        X_train_scaled, X_test_scaled = preprocess_data(X_train, X_test)\n",
    "        \n",
    "        feature_no = X.shape[1]\n",
    "       \n",
    "        feature_map, ansatz_curcuit = create_feature_map(feature_map_type, pca_no, entang)\n",
    "       \n",
    "        \n",
    "        optimizer = create_optimizer(optimizer_type)      \n",
    " \n",
    "        \n",
    "        load_model(model, X_train_scaled, X_test_scaled, y_train, y_test,optimizer,feature_map)\n",
    "        \n",
    "        \n",
    "        \n",
    "        \n",
    "        return render_template('index.html',fmap=feature_map, ans = ansatz_curcuit )\n",
    "        # Handle the GET request and render the form\n",
    "    return render_template('index.html')\n",
    "    \n",
    "\n",
    "    \n",
    "def load_dataset(dataset):\n",
    "    if dataset == 'iris':\n",
    "        iris = datasets.load_iris()\n",
    "        X = iris.data\n",
    "        y = iris.target\n",
    "        return X, y\n",
    "    if dataset == 'diabetes':\n",
    "        diabetes = datasets.load_diabetes()\n",
    "        X = diabetes.data\n",
    "        y = diabetes.target\n",
    "        return X, y\n",
    "    if dataset == 'wine':\n",
    "        wine = datasets.load_wine()\n",
    "        X = wine.data\n",
    "        y = wine.target\n",
    "        return X, y\n",
    "    if dataset == 'cancer':\n",
    "        cancer = datasets.load_breast_cancer()\n",
    "        X = cancer.data\n",
    "        y = cancer.target\n",
    "        return X, y\n",
    "    \n",
    "def split_ratio(split):\n",
    "    if split == '80/20':\n",
    "        return 0.2\n",
    "    else :\n",
    "        return 0.3\n",
    "\n",
    "def preprocess_data(X_train, X_test):\n",
    "    scaler = MinMaxScaler()\n",
    "    X_train_scaled = scaler.fit_transform(X_train)\n",
    "    X_test_scaled = scaler.transform(X_test)\n",
    "    return X_train_scaled, X_test_scaled\n",
    "\n",
    "def draw_and_encode_circuit(circuit):\n",
    "    image_stream = io.BytesIO()\n",
    "    circuit_drawer(circuit, output=\"mpl\", fold=20, filename=image_stream)\n",
    "    image_stream.seek(0)\n",
    "    base64_image = base64.b64encode(image_stream.getvalue()).decode('utf-8')\n",
    "    return base64_image\n",
    "\n",
    "def create_feature_map(feature_map_type, fdimension, entang):\n",
    "    if feature_map_type == 'zz':\n",
    "        # Create the ZZFeatureMap and draw its circuit\n",
    "        feature_map = ZZFeatureMap(feature_dimension=fdimension, reps=1, entanglement=entang)\n",
    "        base64_feature_map_image = draw_and_encode_circuit(feature_map.decompose())\n",
    "\n",
    "        # Create the RealAmplitudes ansatz and draw its circuit\n",
    "        ansatz = RealAmplitudes(num_qubits=fdimension, reps=3)\n",
    "        base64_ansatz_image = draw_and_encode_circuit(ansatz.decompose())\n",
    "\n",
    "        return base64_feature_map_image, base64_ansatz_image\n",
    "    \n",
    "    elif feature_map_type == 'z':\n",
    "        # Create the ZFeatureMap and draw its circuit\n",
    "        feature_map = ZFeatureMap(feature_dimension=fdimension, reps=1, entanglement=entang)\n",
    "        base64_feature_map_image = draw_and_encode_circuit(feature_map.decompose())\n",
    "\n",
    "        # Create the RealAmplitudes ansatz and draw its circuit\n",
    "        ansatz = RealAmplitudes(num_qubits=fdimension, reps=3)\n",
    "        base64_ansatz_image = draw_and_encode_circuit(ansatz.decompose())\n",
    "\n",
    "        return base64_feature_map_image, base64_ansatz_image\n",
    "    \n",
    "    elif feature_map_type == 'pauli':\n",
    "        # Create the ZZFeatureMap and draw its circuit\n",
    "        feature_map = PauliFeatureMap(feature_dimension=fdimension, reps=1, entanglement=entang)\n",
    "        base64_feature_map_image = draw_and_encode_circuit(feature_map.decompose())\n",
    "\n",
    "        # Create the RealAmplitudes ansatz and draw its circuit\n",
    "        ansatz = RealAmplitudes(num_qubits=fdimension, reps=3)\n",
    "        base64_ansatz_image = draw_and_encode_circuit(ansatz.decompose())\n",
    "\n",
    "        return base64_feature_map_image, base64_ansatz_image\n",
    "\n",
    "def create_optimizer(optimizer_type):\n",
    "    if optimizer_type == 'spsa':\n",
    "        return SPSA(maxiter=100)\n",
    "    if optimizer_type == 'coby':\n",
    "        return COBYLA(maxiter=100)\n",
    "    if optimizer_type == 'adam':\n",
    "        return COBYLA(maxiter=100)\n",
    "    \n",
    "def pca(pca_no,X):\n",
    "    pca = decomposition.PCA(n_components=pca_no)\n",
    "    pca.fit(X)\n",
    "    X = pca.transform(X)\n",
    "    return X\n",
    "\n",
    "def load_model(model, X_train_scaled, X_test_scaled, y_train, y_test,optimizer,feature_map):\n",
    "    if model == \"MLP/VQC\":\n",
    "        c_metrics = mlp_classifier(X_train_scaled, X_test_scaled, y_train, y_test)\n",
    "        q_metrics = vqc_classifier(optimizer,feature_map,ansatz, X_train_scaled, X_test_scaled, y_train, y_test)\n",
    "        bchart = barchart_mlp_vqc(c_metrics,q_metrics)\n",
    "        return bchart\n",
    "    if model == \"SVM/QSVM\":\n",
    "        c_metrics = svm_classifie(X_train_scaled, X_test_scaled, y_train, y_test)\n",
    "        q_metrics = qsvm_classifier(feature_map,X_train_scaled, X_test_scaled, y_train, y_test)\n",
    "        bchart = barchart_mlp_vqc(c_metrics,q_metrics)\n",
    "        return bchart\n",
    "    if model == \"SVC/QSVC\":\n",
    "        c_metrics = svc_classifie(X_train_scaled, X_test_scaled, y_train, y_test)\n",
    "        q_metrics = qsvc_classifier(feature_map,X_train_scaled, X_test_scaled, y_train, y_test)\n",
    "        bchart = barchart_mlp_vqc(c_metrics,q_metrics)\n",
    "        return bchart\n",
    "    if model == \"LR/VQC\":\n",
    "        c_metrics = lr_classifie(X_train_scaled, X_test_scaled, y_train, y_test)\n",
    "        q_metrics = vqc_classifier(optimizer,feature_map,ansatz,X_train_scaled, X_test_scaled, y_train, y_test)\n",
    "        bchart = barchart_mlp_vqc(c_metrics,q_metrics)\n",
    "        return bchart\n",
    "\n",
    "#=============================== MLP / VQC CLASSIFIER==========================\n",
    "\n",
    "def mlp_classifer( X_train_scaled, X_test_scaled, y_train, y_test):\n",
    "    # Create an instance of the MLP classifier\n",
    "    mlp = MLPClassifier(hidden_layer_sizes=(50,), max_iter=5000, random_state=42)\n",
    "    # Train the MLP classifier\n",
    "    mlp.fit(X_train_scaled, y_train_scaled)\n",
    "    # Make predictions with MLP classifier\n",
    "    y_pred_mlp = mlp.predict(X_test_scaled)\n",
    "    # Calculate accuracy, F1 score, precision, and recall for MLP classifier\n",
    "    accuracy_mlp = accuracy_score(y_test, y_pred_mlp)\n",
    "    f1_mlp = f1_score(y_test, y_pred_mlp, average='weighted')\n",
    "    precision_mlp = precision_score(y_test, y_pred_mlp, average='weighted')\n",
    "    recall_mlp = recall_score(y_test, y_pred_mlp, average='weighted')    \n",
    "    return accuracy_mlp,f1_mlp,precision_mlp, recall_mlp\n",
    "\n",
    "objective_func_vals = []\n",
    "plt.rcParams[\"figure.figsize\"] = (12, 6)\n",
    "\n",
    "def callback_graph(weights, obj_func_eval):\n",
    "    clear_output(wait=True)\n",
    "    objective_func_vals.append(obj_func_eval)\n",
    "    plt.title(\"Objective function value against iteration\")\n",
    "    plt.xlabel(\"Iteration\")\n",
    "    plt.ylabel(\"Objective function value\")\n",
    "    plt.plot(range(len(objective_func_vals)), objective_func_vals)\n",
    "    plt.show()\n",
    "    \n",
    "def vqc_classifier(optimizer,feature_map,ansatz, X_train_scaled, X_test_scaled, y_train, y_test):\n",
    "    optimizer = COBYLA(maxiter=100)\n",
    "    sampler = Sampler()\n",
    "    vqc = VQC(\n",
    "    feature_map=feature_map,\n",
    "    ansatz=ansatz,\n",
    "    optimizer=optimizer,\n",
    "    callback=callback_graph,\n",
    "    sampler=sampler\n",
    "    )\n",
    "    vqc.fit(X_train, y_train)\n",
    "    # Make predictions with VQC\n",
    "    y_pred_vqc = vqc.predict(X_test_scaled)\n",
    "    # Calculate accuracy, F1 score, precision, and recall for VQC\n",
    "    accuracy_vqc = accuracy_score(y_test, y_pred_vqc)\n",
    "    f1_vqc = f1_score(y_test, y_pred_vqc, average='weighted')\n",
    "    precision_vqc = precision_score(y_test, y_pred_vqc, average='weighted')\n",
    "    recall_vqc = recall_score(y_test, y_pred_vqc, average='weighted')\n",
    "    return accuracy_vqc,f1_vqc,precision_vqc, recall_vqc\n",
    "\n",
    "def barchart_mlp_vqc():\n",
    "    # Bar chart\n",
    "    labels = ['Accuracy', 'Precision', 'Recall', 'F1 Score']\n",
    "    svm_scores = [accuracy_mlp, precision_mlp, recall_mlp, f1_mlp]\n",
    "    qsvm_scores = [accuracy_vqc, precision_vqc, recall_vqc, f1_vqc]\n",
    "\n",
    "    x = np.arange(len(labels))\n",
    "    width = 0.35\n",
    "\n",
    "    fig, ax = plt.subplots()\n",
    "    rects1 = ax.bar(x - width/2, svm_scores, width, label='MLP')\n",
    "    rects2 = ax.bar(x + width/2, qsvm_scores, width, label='VQC')\n",
    "\n",
    "    ax.set_ylabel('Scores')\n",
    "    ax.set_title('Comparison of Metrics: MLP vs VQC')\n",
    "    ax.set_xticks(x)\n",
    "    ax.set_xticklabels(labels)\n",
    "    ax.legend()\n",
    "\n",
    "    ax.bar_label(rects1, padding=3)\n",
    "    ax.bar_label(rects2, padding=3)\n",
    "\n",
    "    fig.tight_layout()\n",
    "\n",
    "    plt.show()\n",
    "    \n",
    "   \n",
    "  \n",
    "#================================= QSVM/SVM======================================================\n",
    "\n",
    "def svm_classifier(X_train_scaled, X_test_scaled, y_train, y_test):\n",
    "    svm = svm.SVC(kernel='linear')\n",
    "    svm.fit(X_train, y_train)\n",
    "    svm_pred = svm.predict(X_test)\n",
    "    \n",
    "    svm_accuracy = accuracy_score(y_test, svm_pred)\n",
    "    svm_precision = precision_score(y_test, svm_pred, average='macro')\n",
    "    svm_recall = recall_score(y_test, svm_pred, average='macro')\n",
    "    svm_f1 = f1_score(y_test, svm_pred, average='macro')\n",
    "    return svm_accuracy,svm_precision, svm_recall,svm_f1\n",
    "    \n",
    "    \n",
    "def qsvm_classifier(feature_map, X_train_scaled, X_test_scaled, y_train, y_test):\n",
    "    \n",
    "    qkernel = QuantumKernel(feature_map=feature_map, quantum_instance=Aer.get_backend('qasm_simulator'))\n",
    "    qsvm = QSVC(quantum_kernel=qkernel)\n",
    "    start = time.time()\n",
    "    epochs = 10\n",
    "    for _ in tqdm(range(epochs), desc=\"Training Progress\"):\n",
    "        qsvm.fit(X_train, y_train)\n",
    "    elapsed = time.time() - start\n",
    "    # Predict labels for the test set\n",
    "    y_pred = qsvm.predict(X_test)\n",
    "    cm = confusion_matrix(y_test, y_pred)\n",
    "    qsvm_accuracy = np.sum(y_pred == y_test) / len(y_test)\n",
    "    qsvm_f1 = f1_score(y_test, y_pred, average='weighted')\n",
    "    qsvm_precision = precision_score(y_test, y_pred, average='weighted')\n",
    "    qsvm_recall = recall_score(y_test, y_pred, average='weighted')\n",
    "    \n",
    "    return qsvm_accuracy,qsvm_f1,qsvm_precision,qsvm_recall\n",
    "    \n",
    "def barchart_qsvm_svm():\n",
    "    # Bar chart\n",
    "    labels = ['Accuracy', 'Precision', 'Recall', 'F1 Score']\n",
    "    svm_scores = [svm_accuracy, svm_precision, svm_recall, svm_f1]\n",
    "    qsvm_scores = [qsvm_accuracy, qsvm_precision, qsvm_recall, qsvm_f1]\n",
    "\n",
    "    x = np.arange(len(labels))\n",
    "    width = 0.35\n",
    "\n",
    "    fig, ax = plt.subplots()\n",
    "    rects1 = ax.bar(x - width/2, svm_scores, width, label='SVM')\n",
    "    rects2 = ax.bar(x + width/2, qsvm_scores, width, label='QSVM')\n",
    "\n",
    "    ax.set_ylabel('Scores')\n",
    "    ax.set_title('Comparison of Metrics: SVM vs QSVM')\n",
    "    ax.set_xticks(x)\n",
    "    ax.set_xticklabels(labels)\n",
    "    ax.legend()\n",
    "\n",
    "    ax.bar_label(rects1, padding=3)\n",
    "    ax.bar_label(rects2, padding=3)\n",
    "\n",
    "    fig.tight_layout()\n",
    "\n",
    "    plt.show()\n",
    "    \n",
    "#================================QSVC/SVC======================================================\n",
    "\n",
    "def svc_classifier(X_train_scaled, X_test_scaled, y_train, y_test):\n",
    "    svc = SVC()\n",
    "    svc.fit(X_train, y_train) \n",
    "    svc_pred = svc.predict(X_test)\n",
    "    \n",
    "    svc_accuracy = accuracy_score(y_test, svc_pred)\n",
    "    svc_precision = precision_score(y_test, svc_pred, average='macro')\n",
    "    svc_recall = recall_score(y_test, svc_pred, average='macro')\n",
    "    svc_f1 = f1_score(y_test, svc_pred, average='macro')\n",
    "    return svc_accuracy,svc_precision, svc_recall,svc_f1\n",
    "\n",
    "def qsvc_classifier(feature_map, X_train_scaled, X_test_scaled, y_train, y_test,backend):\n",
    "    sampler = Sampler()\n",
    "    fidelity = ComputeUncompute(sampler=sampler)\n",
    "    kernel = FidelityQuantumKernel(fidelity=fidelity, feature_map=feature_map)\n",
    "    qsvc = QSVC(quantum_kernel=kernel)\n",
    "    start = time.time()\n",
    "    qsvc.fit(X_train, y_train)\n",
    "    elapsed = time.time() - start\n",
    "    y_pred = qsvc.predict(X_test)\n",
    "    cm = confusion_matrix(y_test, y_pred)\n",
    "    qsvc_accuracy = np.sum(y_pred == y_test) / len(y_test)\n",
    "    qsvc_f1 = f1_score(y_test, y_pred, average='weighted')\n",
    "    qsvc_precision = precision_score(y_test, y_pred, average='weighted')\n",
    "    qsvc_recall = recall_score(y_test, y_pred, average='weighted')    \n",
    "    return qsvc_accuracy,qsvc_f1,qsvc_precision,qsvc_recall\n",
    "\n",
    "\n",
    "#================================VQC/LR======================================================\n",
    "\n",
    "\n",
    "    \n",
    "def lr_classifier():\n",
    "    # Create a logistic regression CL_model_LR\n",
    "    CL_model_LR = LogisticRegression()\n",
    "    # Train the CL_model_LR\n",
    "    CL_model_LR.fit(train_features, train_labels)\n",
    "    # Make predictions on the test set\n",
    "    y_pred_model1 = CL_model_LR.predict(test_features)\n",
    "    svc_accuracy = accuracy_score(y_test, svc_pred)\n",
    "    svc_precision = precision_score(y_test, svc_pred, average='macro')\n",
    "    svc_recall = recall_score(y_test, svc_pred, average='macro')\n",
    "    svc_f1 = f1_score(y_test, svc_pred, average='macro')\n",
    "    return svc_accuracy,svc_precision, svc_recall,svc_f1\n",
    "\n",
    "\n",
    "objective_func_vals = []\n",
    "plt.rcParams[\"figure.figsize\"] = (12, 6)\n",
    "\n",
    "def callback_graph(weights, obj_func_eval):\n",
    "    clear_output(wait=True)\n",
    "    objective_func_vals.append(obj_func_eval)\n",
    "    plt.title(\"Objective function value against iteration\")\n",
    "    plt.xlabel(\"Iteration\")\n",
    "    plt.ylabel(\"Objective function value\")\n",
    "    plt.plot(range(len(objective_func_vals)), objective_func_vals)\n",
    "    plt.show()\n",
    "\n",
    "def ansatz_cir(N):\n",
    "    image_stream = io.BytesIO()\n",
    "    ansatz = RealAmplitudes(num_qubits=N, reps=3)\n",
    "    ansatz.decompose().draw(output=\"mpl\", fold=20,filename=image_stream )\n",
    "    image_stream.seek(0)\n",
    "    base64_image = base64.b64encode(image_stream.getvalue()).decode('utf-8')\n",
    "    return base64_image\n",
    "\n",
    "    \n",
    "@app.route('/get_graph_data')\n",
    "def get_graph_data():\n",
    "    # Return the current timestamp as a unique parameter to prevent caching\n",
    "    timestamp = int(time.time() * 1000)\n",
    "    return jsonify({'graph_src': f'static/graph.jpg?{timestamp}'})\n",
    "\n",
    "\n",
    "@app.route('/quantum_job')\n",
    "def quantum_job_route():\n",
    "    if quantum_job.training_complete:\n",
    "        quantum_job.run_quantum_job() \n",
    "        quantum_job.training_complete = False\n",
    "        \n",
    "        return jsonify({'result': 'success', 'progress': 0})\n",
    "    else:\n",
    "        return jsonify({'result': 'training_in_progress', 'progress': quantum_job.progress})\n",
    "\n",
    "@app.route('/get_hist')\n",
    "def get_hist():\n",
    "     # Return the current timestamp as a unique parameter to prevent caching\n",
    "    timestamp = int(time.time() * 4000)\n",
    "    return jsonify({'hist_src': f'static/histogram.jpg?{timestamp}'})\n",
    "\n",
    "    \n",
    "  \n",
    "  \n",
    "\n",
    "    \n",
    "\n",
    "if __name__ == '__main__':\n",
    "    app.run(port=5887, debug=False, use_reloader=False)   \n",
    "    \n",
    "def connect_to_backend(backend_name):\n",
    "    if backend_name == 'local':\n",
    "        return Aer.get_backend('statevector_simulator')\n",
    "    elif backend_name == 'ionq':\n",
    "        provider = AzureQuantumProvider(\n",
    "            resource_id='/subscriptions/your_subscription_id/resourceGroups/your_resource_group/providers/Microsoft.Quantum/Workspaces/your_workspace_id',\n",
    "            location='your_location'\n",
    "        )\n",
    "        return provider.get_backend('ionq.qpu.h1')\n",
    "    # Add more backends here if needed\n",
    "\n",
    "if __name__ == '__main__':\n",
    "    app.run(port=5044,debug=False,use_reloader=False)\n",
    "    "
   ]
  },
  {
   "cell_type": "code",
   "execution_count": null,
   "id": "92de78dd",
   "metadata": {},
   "outputs": [],
   "source": []
  }
 ],
 "metadata": {
  "kernelspec": {
   "display_name": "Python 3 (ipykernel)",
   "language": "python",
   "name": "python3"
  },
  "language_info": {
   "codemirror_mode": {
    "name": "ipython",
    "version": 3
   },
   "file_extension": ".py",
   "mimetype": "text/x-python",
   "name": "python",
   "nbconvert_exporter": "python",
   "pygments_lexer": "ipython3",
   "version": "3.10.9"
  }
 },
 "nbformat": 4,
 "nbformat_minor": 5
}
